<?php /** @noinspection SpellCheckingInspection */

namespace Tactics\ISO3166\Enum\ISO3166_1;

use Tactics\ISO3166\CountryCode;

enum Alpha2 : string implements CountryCode
{
    case AFGHANISTAN = 'AF';
    case AALAND_ISLANDS = 'AX';
    case ALBANIA = 'AL';
    case ALGERIA = 'DZ';
    case AMERICAN_SAMOA = 'AS';
    case ANDORRA = 'AD';
    case ANGOLA = 'AO';
    case ANGUILLA = 'AI';
    case ANTARCTICA = 'AQ';
    case ANTIGUA_BARBUDA = 'AG';
    case ARGENTINA = 'AR';
    case ARMENIA = 'AM';
    case ARUBA = 'AW';
    case AUSTRALIA = 'AU';
    case AUSTRIA = 'AT';
    case AZERBAIJAN = 'AZ';
    case BAHAMAS = 'BS';
    case BAHRAIN = 'BH';
    case BANGLADESH = 'BD';
    case BARBADOS = 'BB';
    case BELARUS = 'BY';
    case BELGIUM = 'BE';
    case BELIZE = 'BZ';
    case BENIN = 'BJ';
    case BERMUDA = 'BM';
    case BHUTAN = 'BT';
    case BOLIVIA = 'BO';
    case BOSNIA_HERZEGOVINA = 'BA';
    case BOTSWANA = 'BW';
    case BOUVET_ISLAND = 'BV';
    case BRAZIL = 'BR';
    case BRITISH_INDIAN_OCEAN_TERRITORY = 'IO';
    case BRITISH_VIRGIN_ISLANDS = 'VG';
    case BRUNEI = 'BN';
    case BULGARIA = 'BG';
    case BURKINA_FASO = 'BF';
    case BURUNDI = 'BI';
    case CAMBODIA = 'KH';
    case CAMEROON = 'CM';
    case CANADA = 'CA';
    case CAPE_VERDE = 'CV';
    case CARIBBEAN_NETHERLANDS = 'BQ';
    case CAYMAN_ISLANDS = 'KY';
    case CENTRAL_AFRICAN_REPUBLIC = 'CF';
    case CHAD = 'TD';
    case CHILE = 'CL';
    case CHINA = 'CN';
    case CHRISTMAS_ISLAND = 'CX';
    case COCOS_KEELING_ISLANDS = 'CC';
    case COLOMBIA = 'CO';
    case COMOROS = 'KM';
    case CONGO_BRAZZAVILLE = 'CG';
    case CONGO_KINSHASA = 'CD';
    case COOK_ISLANDS = 'CK';
    case COSTA_RICA = 'CR';
    case COTE_D_IVOIRE = 'CI';
    case CROATIA = 'HR';
    case CUBA = 'CU';
    case CURACAO = 'CW';
    case CYPRUS = 'CY';
    case CZECHIA = 'CZ';
    case DENMARK = 'DK';
    case DJIBOUTI = 'DJ';
    case DOMINICA = 'DM';
    case DOMINICAN_REPUBLIC = 'DO';
    case ECUADOR = 'EC';
    case EGYPT = 'EG';
    case EL_SALVADOR = 'SV';
    case EQUATORIAL_GUINEA = 'GQ';
    case ERITREA = 'ER';
    case ESTONIA = 'EE';
    case ESWATINI = 'SZ';
    case ETHIOPIA = 'ET';
    case FALKLAND_ISLANDS = 'FK';
    case FAROE_ISLANDS = 'FO';
    case FIJI = 'FJ';
    case FINLAND = 'FI';
    case FRANCE = 'FR';
    case FRENCH_GUIANA = 'GF';
    case FRENCH_POLYNESIA = 'PF';
    case FRENCH_SOUTHERN_TERRITORIES = 'TF';
    case GABON = 'GA';
    case GAMBIA = 'GM';
    case GEORGIA = 'GE';
    case GERMANY = 'DE';
    case GHANA = 'GH';
    case GIBRALTAR = 'GI';
    case GREECE = 'GR';
    case GREENLAND = 'GL';
    case GRENADA = 'GD';
    case GUADELOUPE = 'GP';
    case GUAM = 'GU';
    case GUATEMALA = 'GT';
    case GUERNSEY = 'GG';
    case GUINEA = 'GN';
    case GUINEA_BISSAU = 'GW';
    case GUYANA = 'GY';
    case HAITI = 'HT';
    case HEARD_MCDONALD_ISLANDS = 'HM';
    case HONDURAS = 'HN';
    case HONG_KONG_SAR_CHINA = 'HK';
    case HUNGARY = 'HU';
    case ICELAND = 'IS';
    case INDIA = 'IN';
    case INDONESIA = 'ID';
    case IRAN = 'IR';
    case IRAQ = 'IQ';
    case IRELAND = 'IE';
    case ISLE_OF_MAN = 'IM';
    case ISRAEL = 'IL';
    case ITALY = 'IT';
    case JAMAICA = 'JM';
    case JAPAN = 'JP';
    case JERSEY = 'JE';
    case JORDAN = 'JO';
    case KAZAKHSTAN = 'KZ';

    case KENYA = 'KE';
    case KIRIBATI = 'KI';
    case KUWAIT = 'KW';
    case KYRGYZSTAN = 'KG';
    case LAOS = 'LA';
    case LATVIA = 'LV';
    case LEBANON = 'LB';
    case LESOTHO = 'LS';
    case LIBERIA = 'LR';
    case LIBYA = 'LY';
    case LIECHTENSTEIN = 'LI';
    case LITHUANIA = 'LT';
    case LUXEMBOURG = 'LU';
    case MACAO_SAR_CHINA = 'MO';
    case MADAGASCAR = 'MG';
    case MALAWI = 'MW';
    case MALAYSIA = 'MY';
    case MALDIVES = 'MV';
    case MALI = 'ML';
    case MALTA = 'MT';
    case MARSHALL_ISLANDS = 'MH';
    case MARTINIQUE = 'MQ';
    case MAURITANIA = 'MR';
    case MAURITIUS = 'MU';
    case MAYOTTE = 'YT';
    case MEXICO = 'MX';
    case MICRONESIA = 'FM';
    case MOLDOVA = 'MD';
    case MONACO = 'MC';
    case MONGOLIA = 'MN';
    case MONTENEGRO = 'ME';
    case MONTSERRAT = 'MS';
    case MOROCCO = 'MA';
    case MOZAMBIQUE = 'MZ';
    case MYANMAR_BURMA = 'MM';
    case NAMIBIA = 'NA';
    case NAURU = 'NR';
    case NEPAL = 'NP';
    case NETHERLANDS = 'NL';
    case NEW_CALEDONIA = 'NC';
    case NEW_ZEALAND = 'NZ';
    case NICARAGUA = 'NI';
    case NIGER = 'NE';
    case NIGERIA = 'NG';
    case NIUE = 'NU';
    case NORFOLK_ISLAND = 'NF';
    case NORTH_KOREA = 'KP';
    case NORTH_MACEDONIA = 'MK';
    case NORTHERN_MARIANA_ISLANDS = 'MP';
    case NORWAY = 'NO';
    case OMAN = 'OM';
    case PAKISTAN = 'PK';
    case PALAU = 'PW';
    case PALESTINIAN_TERRITORIES = 'PS';
    case PANAMA = 'PA';
    case PAPUA_NEW_GUINEA = 'PG';
    case PARAGUAY = 'PY';
    case PERU = 'PE';
    case PHILIPPINES = 'PH';
    case PITCAIRN_ISLANDS = 'PN';
    case POLAND = 'PL';
    case PORTUGAL = 'PT';
    case PUERTO_RICO = 'PR';
    case QATAR = 'QA';
    case REUNION = 'RE';
    case ROMANIA = 'RO';
    case RUSSIA = 'RU';
    case RWANDA = 'RW';
    case SAMOA = 'WS';
    case SAN_MARINO = 'SM';
    case SAO_TOME_PRINCIPE = 'ST';
    case SAUDI_ARABIA = 'SA';
    case SENEGAL = 'SN';
    case SERBIA = 'RS';
    case SEYCHELLES = 'SC';
    case SIERRA_LEONE = 'SL';
    case SINGAPORE = 'SG';
    case SINT_MAARTEN = 'SX';
    case SLOVAKIA = 'SK';
    case SLOVENIA = 'SI';
    case SOLOMON_ISLANDS = 'SB';
    case SOMALIA = 'SO';
    case SOUTH_AFRICA = 'ZA';
    case SOUTH_GEORGIA_SOUTH_SANDWICH_ISLANDS = 'GS';
    case SOUTH_KOREA = 'KR';
    case SOUTH_SUDAN = 'SS';
    case SPAIN = 'ES';
    case SRI_LANKA = 'LK';
    case ST_BARTHELEMY = 'BL';
    case ST_HELENA = 'SH';
    case ST_KITTS_NEVIS = 'KN';
    case ST_LUCIA = 'LC';
    case ST_MARTIN = 'MF';
    case ST_PIERRE_MIQUELON = 'PM';
    case ST_VINCENT_GRENADINES = 'VC';
    case SUDAN = 'SD';
    case SURINAME = 'SR';
    case SVALBARD_JAN_MAYEN = 'SJ';
    case SWEDEN = 'SE';
    case SWITZERLAND = 'CH';
    case SYRIA = 'SY';
    case TAIWAN = 'TW';
    case TAJIKISTAN = 'TJ';
    case TANZANIA = 'TZ';
    case THAILAND = 'TH';
    case TIMOR_LESTE = 'TL';
    case TOGO = 'TG';
    case TOKELAU = 'TK';
    case TONGA = 'TO';
    case TRINIDAD_TOBAGO = 'TT';
    case TUNISIA = 'TN';
    case TURKEY = 'TR';
    case TURKMENISTAN = 'TM';
    case TURKS_CAICOS_ISLANDS = 'TC';
    case TUVALU = 'TV';
    case U_S_OUTLYING_ISLANDS = 'UM';
    case U_S_VIRGIN_ISLANDS = 'VI';
    case UGANDA = 'UG';
    case UKRAINE = 'UA';
    case UNITED_ARAB_EMIRATES = 'AE';
    case UNITED_KINGDOM = 'GB';
    case UNITED_STATES = 'US';
    case URUGUAY = 'UY';
    case UZBEKISTAN = 'UZ';
    case VANUATU = 'VU';
    case VATICAN_CITY = 'VA';
    case VENEZUELA = 'VE';
    case VIETNAM = 'VN';
    case WALLIS_FUTUNA = 'WF';
    case WESTERN_SAHARA = 'EH';
    case YEMEN = 'YE';
    case ZAMBIA = 'ZM';
    case ZIMBABWE = 'ZW';

    public function asAlpha3(): Alpha3
    {
        return match($this) {
            self::AFGHANISTAN => Alpha3::AFGHANISTAN,
            self::AALAND_ISLANDS => Alpha3::AALAND_ISLANDS,
            self::ALBANIA => Alpha3::ALBANIA,
            self::ALGERIA => Alpha3::ALGERIA,
            self::AMERICAN_SAMOA => Alpha3::AMERICAN_SAMOA,
            self::ANDORRA => Alpha3::ANDORRA,
            self::ANGOLA => Alpha3::ANGOLA,
            self::ANGUILLA => Alpha3::ANGUILLA,
            self::ANTARCTICA => Alpha3::ANTARCTICA,
            self::ANTIGUA_BARBUDA => Alpha3::ANTIGUA_BARBUDA,
            self::ARGENTINA => Alpha3::ARGENTINA,
            self::ARMENIA => Alpha3::ARMENIA,
            self::ARUBA => Alpha3::ARUBA,
            self::AUSTRALIA => Alpha3::AUSTRALIA,
            self::AUSTRIA => Alpha3::AUSTRIA,
            self::AZERBAIJAN => Alpha3::AZERBAIJAN,
            self::BAHAMAS => Alpha3::BAHAMAS,
            self::BAHRAIN => Alpha3::BAHRAIN,
            self::BANGLADESH => Alpha3::BANGLADESH,
            self::BARBADOS => Alpha3::BARBADOS,
            self::BELARUS => Alpha3::BELARUS,
            self::BELGIUM => Alpha3::BELGIUM,
            self::BELIZE => Alpha3::BELIZE,
            self::BENIN => Alpha3::BENIN,
            self::BERMUDA => Alpha3::BERMUDA,
            self::BHUTAN => Alpha3::BHUTAN,
            self::BOLIVIA => Alpha3::BOLIVIA,
            self::BOSNIA_HERZEGOVINA => Alpha3::BOSNIA_HERZEGOVINA,
            self::BOTSWANA => Alpha3::BOTSWANA,
            self::BOUVET_ISLAND => Alpha3::BOUVET_ISLAND,
            self::BRAZIL => Alpha3::BRAZIL,
            self::BRITISH_INDIAN_OCEAN_TERRITORY => Alpha3::BRITISH_INDIAN_OCEAN_TERRITORY,
            self::BRITISH_VIRGIN_ISLANDS => Alpha3::BRITISH_VIRGIN_ISLANDS,
            self::BRUNEI => Alpha3::BRUNEI,
            self::BULGARIA => Alpha3::BULGARIA,
            self::BURKINA_FASO => Alpha3::BURKINA_FASO,
            self::BURUNDI => Alpha3::BURUNDI,
            self::CAMBODIA => Alpha3::CAMBODIA,
            self::CAMEROON => Alpha3::CAMEROON,
            self::CANADA => Alpha3::CANADA,
            self::CAPE_VERDE => Alpha3::CAPE_VERDE,
            self::CARIBBEAN_NETHERLANDS => Alpha3::CARIBBEAN_NETHERLANDS,
            self::CAYMAN_ISLANDS => Alpha3::CAYMAN_ISLANDS,
            self::CENTRAL_AFRICAN_REPUBLIC => Alpha3::CENTRAL_AFRICAN_REPUBLIC,
            self::CHAD => Alpha3::CHAD,
            self::CHILE => Alpha3::CHILE,
            self::CHINA => Alpha3::CHINA,
            self::CHRISTMAS_ISLAND => Alpha3::CHRISTMAS_ISLAND,
            self::COCOS_KEELING_ISLANDS => Alpha3::COCOS_KEELING_ISLANDS,
            self::COLOMBIA => Alpha3::COLOMBIA,
            self::COMOROS => Alpha3::COMOROS,
            self::CONGO_BRAZZAVILLE => Alpha3::CONGO_BRAZZAVILLE,
            self::CONGO_KINSHASA => Alpha3::CONGO_KINSHASA,
            self::COOK_ISLANDS => Alpha3::COOK_ISLANDS,
            self::COSTA_RICA => Alpha3::COSTA_RICA,
            self::COTE_D_IVOIRE => Alpha3::COTE_D_IVOIRE,
            self::CROATIA => Alpha3::CROATIA,
            self::CUBA => Alpha3::CUBA,
            self::CURACAO => Alpha3::CURACAO,
            self::CYPRUS => Alpha3::CYPRUS,
            self::CZECHIA => Alpha3::CZECHIA,
            self::DENMARK => Alpha3::DENMARK,
            self::DJIBOUTI => Alpha3::DJIBOUTI,
            self::DOMINICA => Alpha3::DOMINICA,
            self::DOMINICAN_REPUBLIC => Alpha3::DOMINICAN_REPUBLIC,
            self::ECUADOR => Alpha3::ECUADOR,
            self::EGYPT => Alpha3::EGYPT,
            self::EL_SALVADOR => Alpha3::EL_SALVADOR,
            self::EQUATORIAL_GUINEA => Alpha3::EQUATORIAL_GUINEA,
            self::ERITREA => Alpha3::ERITREA,
            self::ESTONIA => Alpha3::ESTONIA,
            self::ESWATINI => Alpha3::ESWATINI,
            self::ETHIOPIA => Alpha3::ETHIOPIA,
            self::FALKLAND_ISLANDS => Alpha3::FALKLAND_ISLANDS,
            self::FAROE_ISLANDS => Alpha3::FAROE_ISLANDS,
            self::FIJI => Alpha3::FIJI,
            self::FINLAND => Alpha3::FINLAND,
            self::FRANCE => Alpha3::FRANCE,
            self::FRENCH_GUIANA => Alpha3::FRENCH_GUIANA,
            self::FRENCH_POLYNESIA => Alpha3::FRENCH_POLYNESIA,
            self::FRENCH_SOUTHERN_TERRITORIES => Alpha3::FRENCH_SOUTHERN_TERRITORIES,
            self::GABON => Alpha3::GABON,
            self::GAMBIA => Alpha3::GAMBIA,
            self::GEORGIA => Alpha3::GEORGIA,
            self::GERMANY => Alpha3::GERMANY,
            self::GHANA => Alpha3::GHANA,
            self::GIBRALTAR => Alpha3::GIBRALTAR,
            self::GREECE => Alpha3::GREECE,
            self::GREENLAND => Alpha3::GREENLAND,
            self::GRENADA => Alpha3::GRENADA,
            self::GUADELOUPE => Alpha3::GUADELOUPE,
            self::GUAM => Alpha3::GUAM,
            self::GUATEMALA => Alpha3::GUATEMALA,
            self::GUERNSEY => Alpha3::GUERNSEY,
            self::GUINEA => Alpha3::GUINEA,
            self::GUINEA_BISSAU => Alpha3::GUINEA_BISSAU,
            self::GUYANA => Alpha3::GUYANA,
            self::HAITI => Alpha3::HAITI,
            self::HEARD_MCDONALD_ISLANDS => Alpha3::HEARD_MCDONALD_ISLANDS,
            self::HONDURAS => Alpha3::HONDURAS,
            self::HONG_KONG_SAR_CHINA => Alpha3::HONG_KONG_SAR_CHINA,
            self::HUNGARY => Alpha3::HUNGARY,
            self::ICELAND => Alpha3::ICELAND,
            self::INDIA => Alpha3::INDIA,
            self::INDONESIA => Alpha3::INDONESIA,
            self::IRAN => Alpha3::IRAN,
            self::IRAQ => Alpha3::IRAQ,
            self::IRELAND => Alpha3::IRELAND,
            self::ISLE_OF_MAN => Alpha3::ISLE_OF_MAN,
            self::ISRAEL => Alpha3::ISRAEL,
            self::ITALY => Alpha3::ITALY,
            self::JAMAICA => Alpha3::JAMAICA,
            self::JAPAN => Alpha3::JAPAN,
            self::JERSEY => Alpha3::JERSEY,
            self::JORDAN => Alpha3::JORDAN,
            self::KAZAKHSTAN => Alpha3::KAZAKHSTAN,
            self::KENYA => Alpha3::KENYA,
            self::KIRIBATI => Alpha3::KIRIBATI,
            self::KUWAIT => Alpha3::KUWAIT,
            self::KYRGYZSTAN => Alpha3::KYRGYZSTAN,
            self::LAOS => Alpha3::LAOS,
            self::LATVIA => Alpha3::LATVIA,
            self::LEBANON => Alpha3::LEBANON,
            self::LESOTHO => Alpha3::LESOTHO,
            self::LIBERIA => Alpha3::LIBERIA,
            self::LIBYA => Alpha3::LIBYA,
            self::LIECHTENSTEIN => Alpha3::LIECHTENSTEIN,
            self::LITHUANIA => Alpha3::LITHUANIA,
            self::LUXEMBOURG => Alpha3::LUXEMBOURG,
            self::MACAO_SAR_CHINA => Alpha3::MACAO_SAR_CHINA,
            self::MADAGASCAR => Alpha3::MADAGASCAR,
            self::MALAWI => Alpha3::MALAWI,
            self::MALAYSIA => Alpha3::MALAYSIA,
            self::MALDIVES => Alpha3::MALDIVES,
            self::MALI => Alpha3::MALI,
            self::MALTA => Alpha3::MALTA,
            self::MARSHALL_ISLANDS => Alpha3::MARSHALL_ISLANDS,
            self::MARTINIQUE => Alpha3::MARTINIQUE,
            self::MAURITANIA => Alpha3::MAURITANIA,
            self::MAURITIUS => Alpha3::MAURITIUS,
            self::MAYOTTE => Alpha3::MAYOTTE,
            self::MEXICO => Alpha3::MEXICO,
            self::MICRONESIA => Alpha3::MICRONESIA,
            self::MOLDOVA => Alpha3::MOLDOVA,
            self::MONACO => Alpha3::MONACO,
            self::MONGOLIA => Alpha3::MONGOLIA,
            self::MONTENEGRO => Alpha3::MONTENEGRO,
            self::MONTSERRAT => Alpha3::MONTSERRAT,
            self::MOROCCO => Alpha3::MOROCCO,
            self::MOZAMBIQUE => Alpha3::MOZAMBIQUE,
            self::MYANMAR_BURMA => Alpha3::MYANMAR_BURMA,
            self::NAMIBIA => Alpha3::NAMIBIA,
            self::NAURU => Alpha3::NAURU,
            self::NEPAL => Alpha3::NEPAL,
            self::NETHERLANDS => Alpha3::NETHERLANDS,
            self::NEW_CALEDONIA => Alpha3::NEW_CALEDONIA,
            self::NEW_ZEALAND => Alpha3::NEW_ZEALAND,
            self::NICARAGUA => Alpha3::NICARAGUA,
            self::NIGER => Alpha3::NIGER,
            self::NIGERIA => Alpha3::NIGERIA,
            self::NIUE => Alpha3::NIUE,
            self::NORFOLK_ISLAND => Alpha3::NORFOLK_ISLAND,
            self::NORTH_KOREA => Alpha3::NORTH_KOREA,
            self::NORTH_MACEDONIA => Alpha3::NORTH_MACEDONIA,
            self::NORTHERN_MARIANA_ISLANDS => Alpha3::NORTHERN_MARIANA_ISLANDS,
            self::NORWAY => Alpha3::NORWAY,
            self::OMAN => Alpha3::OMAN,
            self::PAKISTAN => Alpha3::PAKISTAN,
            self::PALAU => Alpha3::PALAU,
            self::PALESTINIAN_TERRITORIES => Alpha3::PALESTINIAN_TERRITORIES,
            self::PANAMA => Alpha3::PANAMA,
            self::PAPUA_NEW_GUINEA => Alpha3::PAPUA_NEW_GUINEA,
            self::PARAGUAY => Alpha3::PARAGUAY,
            self::PERU => Alpha3::PERU,
            self::PHILIPPINES => Alpha3::PHILIPPINES,
            self::PITCAIRN_ISLANDS => Alpha3::PITCAIRN_ISLANDS,
            self::POLAND => Alpha3::POLAND,
            self::PORTUGAL => Alpha3::PORTUGAL,
            self::PUERTO_RICO => Alpha3::PUERTO_RICO,
            self::QATAR => Alpha3::QATAR,
            self::REUNION => Alpha3::REUNION,
            self::ROMANIA => Alpha3::ROMANIA,
            self::RUSSIA => Alpha3::RUSSIA,
            self::RWANDA => Alpha3::RWANDA,
            self::SAMOA => Alpha3::SAMOA,
            self::SAN_MARINO => Alpha3::SAN_MARINO,
            self::SAO_TOME_PRINCIPE => Alpha3::SAO_TOME_PRINCIPE,
            self::SAUDI_ARABIA => Alpha3::SAUDI_ARABIA,
            self::SENEGAL => Alpha3::SENEGAL,
            self::SERBIA => Alpha3::SERBIA,
            self::SEYCHELLES => Alpha3::SEYCHELLES,
            self::SIERRA_LEONE => Alpha3::SIERRA_LEONE,
            self::SINGAPORE => Alpha3::SINGAPORE,
            self::SINT_MAARTEN => Alpha3::SINT_MAARTEN,
            self::SLOVAKIA => Alpha3::SLOVAKIA,
            self::SLOVENIA => Alpha3::SLOVENIA,
            self::SOLOMON_ISLANDS => Alpha3::SOLOMON_ISLANDS,
            self::SOMALIA => Alpha3::SOMALIA,
            self::SOUTH_AFRICA => Alpha3::SOUTH_AFRICA,
            self::SOUTH_GEORGIA_SOUTH_SANDWICH_ISLANDS => Alpha3::SOUTH_GEORGIA_SOUTH_SANDWICH_ISLANDS,
            self::SOUTH_KOREA => Alpha3::SOUTH_KOREA,
            self::SOUTH_SUDAN => Alpha3::SOUTH_SUDAN,
            self::SPAIN => Alpha3::SPAIN,
            self::SRI_LANKA => Alpha3::SRI_LANKA,
            self::ST_BARTHELEMY => Alpha3::ST_BARTHELEMY,
            self::ST_HELENA => Alpha3::ST_HELENA,
            self::ST_KITTS_NEVIS => Alpha3::ST_KITTS_NEVIS,
            self::ST_LUCIA => Alpha3::ST_LUCIA,
            self::ST_MARTIN => Alpha3::ST_MARTIN,
            self::ST_PIERRE_MIQUELON => Alpha3::ST_PIERRE_MIQUELON,
            self::ST_VINCENT_GRENADINES => Alpha3::ST_VINCENT_GRENADINES,
            self::SUDAN => Alpha3::SUDAN,
            self::SURINAME => Alpha3::SURINAME,
            self::SVALBARD_JAN_MAYEN => Alpha3::SVALBARD_JAN_MAYEN,
            self::SWEDEN => Alpha3::SWEDEN,
            self::SWITZERLAND => Alpha3::SWITZERLAND,
            self::SYRIA => Alpha3::SYRIA,
            self::TAIWAN => Alpha3::TAIWAN,
            self::TAJIKISTAN => Alpha3::TAJIKISTAN,
            self::TANZANIA => Alpha3::TANZANIA,
            self::THAILAND => Alpha3::THAILAND,
            self::TIMOR_LESTE => Alpha3::TIMOR_LESTE,
            self::TOGO => Alpha3::TOGO,
            self::TOKELAU => Alpha3::TOKELAU,
            self::TONGA => Alpha3::TONGA,
            self::TRINIDAD_TOBAGO => Alpha3::TRINIDAD_TOBAGO,
            self::TUNISIA => Alpha3::TUNISIA,
            self::TURKEY => Alpha3::TURKEY,
            self::TURKMENISTAN => Alpha3::TURKMENISTAN,
            self::TURKS_CAICOS_ISLANDS => Alpha3::TURKS_CAICOS_ISLANDS,
            self::TUVALU => Alpha3::TUVALU,
            self::U_S_OUTLYING_ISLANDS => Alpha3::U_S_OUTLYING_ISLANDS,
            self::U_S_VIRGIN_ISLANDS => Alpha3::U_S_VIRGIN_ISLANDS,
            self::UGANDA => Alpha3::UGANDA,
            self::UKRAINE => Alpha3::UKRAINE,
            self::UNITED_ARAB_EMIRATES => Alpha3::UNITED_ARAB_EMIRATES,
            self::UNITED_KINGDOM => Alpha3::UNITED_KINGDOM,
            self::UNITED_STATES => Alpha3::UNITED_STATES,
            self::URUGUAY => Alpha3::URUGUAY,
            self::UZBEKISTAN => Alpha3::UZBEKISTAN,
            self::VANUATU => Alpha3::VANUATU,
            self::VATICAN_CITY => Alpha3::VATICAN_CITY,
            self::VENEZUELA => Alpha3::VENEZUELA,
            self::VIETNAM => Alpha3::VIETNAM,
            self::WALLIS_FUTUNA => Alpha3::WALLIS_FUTUNA,
            self::WESTERN_SAHARA => Alpha3::WESTERN_SAHARA,
            self::YEMEN => Alpha3::YEMEN,
            self::ZAMBIA => Alpha3::ZAMBIA,
            self::ZIMBABWE => Alpha3::ZIMBABWE
        };
    }

    public function asNumeric(): Numeric
    {
        return match($this) {
            self::AFGHANISTAN => Numeric::AFGHANISTAN,
            self::AALAND_ISLANDS => Numeric::AALAND_ISLANDS,
            self::ALBANIA => Numeric::ALBANIA,
            self::ALGERIA => Numeric::ALGERIA,
            self::AMERICAN_SAMOA => Numeric::AMERICAN_SAMOA,
            self::ANDORRA => Numeric::ANDORRA,
            self::ANGOLA => Numeric::ANGOLA,
            self::ANGUILLA => Numeric::ANGUILLA,
            self::ANTARCTICA => Numeric::ANTARCTICA,
            self::ANTIGUA_BARBUDA => Numeric::ANTIGUA_BARBUDA,
            self::ARGENTINA => Numeric::ARGENTINA,
            self::ARMENIA => Numeric::ARMENIA,
            self::ARUBA => Numeric::ARUBA,
            self::AUSTRALIA => Numeric::AUSTRALIA,
            self::AUSTRIA => Numeric::AUSTRIA,
            self::AZERBAIJAN => Numeric::AZERBAIJAN,
            self::BAHAMAS => Numeric::BAHAMAS,
            self::BAHRAIN => Numeric::BAHRAIN,
            self::BANGLADESH => Numeric::BANGLADESH,
            self::BARBADOS => Numeric::BARBADOS,
            self::BELARUS => Numeric::BELARUS,
            self::BELGIUM => Numeric::BELGIUM,
            self::BELIZE => Numeric::BELIZE,
            self::BENIN => Numeric::BENIN,
            self::BERMUDA => Numeric::BERMUDA,
            self::BHUTAN => Numeric::BHUTAN,
            self::BOLIVIA => Numeric::BOLIVIA,
            self::BOSNIA_HERZEGOVINA => Numeric::BOSNIA_HERZEGOVINA,
            self::BOTSWANA => Numeric::BOTSWANA,
            self::BOUVET_ISLAND => Numeric::BOUVET_ISLAND,
            self::BRAZIL => Numeric::BRAZIL,
            self::BRITISH_INDIAN_OCEAN_TERRITORY => Numeric::BRITISH_INDIAN_OCEAN_TERRITORY,
            self::BRITISH_VIRGIN_ISLANDS => Numeric::BRITISH_VIRGIN_ISLANDS,
            self::BRUNEI => Numeric::BRUNEI,
            self::BULGARIA => Numeric::BULGARIA,
            self::BURKINA_FASO => Numeric::BURKINA_FASO,
            self::BURUNDI => Numeric::BURUNDI,
            self::CAMBODIA => Numeric::CAMBODIA,
            self::CAMEROON => Numeric::CAMEROON,
            self::CANADA => Numeric::CANADA,
            self::CAPE_VERDE => Numeric::CAPE_VERDE,
            self::CARIBBEAN_NETHERLANDS => Numeric::CARIBBEAN_NETHERLANDS,
            self::CAYMAN_ISLANDS => Numeric::CAYMAN_ISLANDS,
            self::CENTRAL_AFRICAN_REPUBLIC => Numeric::CENTRAL_AFRICAN_REPUBLIC,
            self::CHAD => Numeric::CHAD,
            self::CHILE => Numeric::CHILE,
            self::CHINA => Numeric::CHINA,
            self::CHRISTMAS_ISLAND => Numeric::CHRISTMAS_ISLAND,
            self::COCOS_KEELING_ISLANDS => Numeric::COCOS_KEELING_ISLANDS,
            self::COLOMBIA => Numeric::COLOMBIA,
            self::COMOROS => Numeric::COMOROS,
            self::CONGO_BRAZZAVILLE => Numeric::CONGO_BRAZZAVILLE,
            self::CONGO_KINSHASA => Numeric::CONGO_KINSHASA,
            self::COOK_ISLANDS => Numeric::COOK_ISLANDS,
            self::COSTA_RICA => Numeric::COSTA_RICA,
            self::COTE_D_IVOIRE => Numeric::COTE_D_IVOIRE,
            self::CROATIA => Numeric::CROATIA,
            self::CUBA => Numeric::CUBA,
            self::CURACAO => Numeric::CURACAO,
            self::CYPRUS => Numeric::CYPRUS,
            self::CZECHIA => Numeric::CZECHIA,
            self::DENMARK => Numeric::DENMARK,
            self::DJIBOUTI => Numeric::DJIBOUTI,
            self::DOMINICA => Numeric::DOMINICA,
            self::DOMINICAN_REPUBLIC => Numeric::DOMINICAN_REPUBLIC,
            self::ECUADOR => Numeric::ECUADOR,
            self::EGYPT => Numeric::EGYPT,
            self::EL_SALVADOR => Numeric::EL_SALVADOR,
            self::EQUATORIAL_GUINEA => Numeric::EQUATORIAL_GUINEA,
            self::ERITREA => Numeric::ERITREA,
            self::ESTONIA => Numeric::ESTONIA,
            self::ESWATINI => Numeric::ESWATINI,
            self::ETHIOPIA => Numeric::ETHIOPIA,
            self::FALKLAND_ISLANDS => Numeric::FALKLAND_ISLANDS,
            self::FAROE_ISLANDS => Numeric::FAROE_ISLANDS,
            self::FIJI => Numeric::FIJI,
            self::FINLAND => Numeric::FINLAND,
            self::FRANCE => Numeric::FRANCE,
            self::FRENCH_GUIANA => Numeric::FRENCH_GUIANA,
            self::FRENCH_POLYNESIA => Numeric::FRENCH_POLYNESIA,
            self::FRENCH_SOUTHERN_TERRITORIES => Numeric::FRENCH_SOUTHERN_TERRITORIES,
            self::GABON => Numeric::GABON,
            self::GAMBIA => Numeric::GAMBIA,
            self::GEORGIA => Numeric::GEORGIA,
            self::GERMANY => Numeric::GERMANY,
            self::GHANA => Numeric::GHANA,
            self::GIBRALTAR => Numeric::GIBRALTAR,
            self::GREECE => Numeric::GREECE,
            self::GREENLAND => Numeric::GREENLAND,
            self::GRENADA => Numeric::GRENADA,
            self::GUADELOUPE => Numeric::GUADELOUPE,
            self::GUAM => Numeric::GUAM,
            self::GUATEMALA => Numeric::GUATEMALA,
            self::GUERNSEY => Numeric::GUERNSEY,
            self::GUINEA => Numeric::GUINEA,
            self::GUINEA_BISSAU => Numeric::GUINEA_BISSAU,
            self::GUYANA => Numeric::GUYANA,
            self::HAITI => Numeric::HAITI,
            self::HEARD_MCDONALD_ISLANDS => Numeric::HEARD_MCDONALD_ISLANDS,
            self::HONDURAS => Numeric::HONDURAS,
            self::HONG_KONG_SAR_CHINA => Numeric::HONG_KONG_SAR_CHINA,
            self::HUNGARY => Numeric::HUNGARY,
            self::ICELAND => Numeric::ICELAND,
            self::INDIA => Numeric::INDIA,
            self::INDONESIA => Numeric::INDONESIA,
            self::IRAN => Numeric::IRAN,
            self::IRAQ => Numeric::IRAQ,
            self::IRELAND => Numeric::IRELAND,
            self::ISLE_OF_MAN => Numeric::ISLE_OF_MAN,
            self::ISRAEL => Numeric::ISRAEL,
            self::ITALY => Numeric::ITALY,
            self::JAMAICA => Numeric::JAMAICA,
            self::JAPAN => Numeric::JAPAN,
            self::JERSEY => Numeric::JERSEY,
            self::JORDAN => Numeric::JORDAN,
            self::KAZAKHSTAN => Numeric::KAZAKHSTAN,
            self::KENYA => Numeric::KENYA,
            self::KIRIBATI => Numeric::KIRIBATI,
            self::KUWAIT => Numeric::KUWAIT,
            self::KYRGYZSTAN => Numeric::KYRGYZSTAN,
            self::LAOS => Numeric::LAOS,
            self::LATVIA => Numeric::LATVIA,
            self::LEBANON => Numeric::LEBANON,
            self::LESOTHO => Numeric::LESOTHO,
            self::LIBERIA => Numeric::LIBERIA,
            self::LIBYA => Numeric::LIBYA,
            self::LIECHTENSTEIN => Numeric::LIECHTENSTEIN,
            self::LITHUANIA => Numeric::LITHUANIA,
            self::LUXEMBOURG => Numeric::LUXEMBOURG,
            self::MACAO_SAR_CHINA => Numeric::MACAO_SAR_CHINA,
            self::MADAGASCAR => Numeric::MADAGASCAR,
            self::MALAWI => Numeric::MALAWI,
            self::MALAYSIA => Numeric::MALAYSIA,
            self::MALDIVES => Numeric::MALDIVES,
            self::MALI => Numeric::MALI,
            self::MALTA => Numeric::MALTA,
            self::MARSHALL_ISLANDS => Numeric::MARSHALL_ISLANDS,
            self::MARTINIQUE => Numeric::MARTINIQUE,
            self::MAURITANIA => Numeric::MAURITANIA,
            self::MAURITIUS => Numeric::MAURITIUS,
            self::MAYOTTE => Numeric::MAYOTTE,
            self::MEXICO => Numeric::MEXICO,
            self::MICRONESIA => Numeric::MICRONESIA,
            self::MOLDOVA => Numeric::MOLDOVA,
            self::MONACO => Numeric::MONACO,
            self::MONGOLIA => Numeric::MONGOLIA,
            self::MONTENEGRO => Numeric::MONTENEGRO,
            self::MONTSERRAT => Numeric::MONTSERRAT,
            self::MOROCCO => Numeric::MOROCCO,
            self::MOZAMBIQUE => Numeric::MOZAMBIQUE,
            self::MYANMAR_BURMA => Numeric::MYANMAR_BURMA,
            self::NAMIBIA => Numeric::NAMIBIA,
            self::NAURU => Numeric::NAURU,
            self::NEPAL => Numeric::NEPAL,
            self::NETHERLANDS => Numeric::NETHERLANDS,
            self::NEW_CALEDONIA => Numeric::NEW_CALEDONIA,
            self::NEW_ZEALAND => Numeric::NEW_ZEALAND,
            self::NICARAGUA => Numeric::NICARAGUA,
            self::NIGER => Numeric::NIGER,
            self::NIGERIA => Numeric::NIGERIA,
            self::NIUE => Numeric::NIUE,
            self::NORFOLK_ISLAND => Numeric::NORFOLK_ISLAND,
            self::NORTH_KOREA => Numeric::NORTH_KOREA,
            self::NORTH_MACEDONIA => Numeric::NORTH_MACEDONIA,
            self::NORTHERN_MARIANA_ISLANDS => Numeric::NORTHERN_MARIANA_ISLANDS,
            self::NORWAY => Numeric::NORWAY,
            self::OMAN => Numeric::OMAN,
            self::PAKISTAN => Numeric::PAKISTAN,
            self::PALAU => Numeric::PALAU,
            self::PALESTINIAN_TERRITORIES => Numeric::PALESTINIAN_TERRITORIES,
            self::PANAMA => Numeric::PANAMA,
            self::PAPUA_NEW_GUINEA => Numeric::PAPUA_NEW_GUINEA,
            self::PARAGUAY => Numeric::PARAGUAY,
            self::PERU => Numeric::PERU,
            self::PHILIPPINES => Numeric::PHILIPPINES,
            self::PITCAIRN_ISLANDS => Numeric::PITCAIRN_ISLANDS,
            self::POLAND => Numeric::POLAND,
            self::PORTUGAL => Numeric::PORTUGAL,
            self::PUERTO_RICO => Numeric::PUERTO_RICO,
            self::QATAR => Numeric::QATAR,
            self::REUNION => Numeric::REUNION,
            self::ROMANIA => Numeric::ROMANIA,
            self::RUSSIA => Numeric::RUSSIA,
            self::RWANDA => Numeric::RWANDA,
            self::SAMOA => Numeric::SAMOA,
            self::SAN_MARINO => Numeric::SAN_MARINO,
            self::SAO_TOME_PRINCIPE => Numeric::SAO_TOME_PRINCIPE,
            self::SAUDI_ARABIA => Numeric::SAUDI_ARABIA,
            self::SENEGAL => Numeric::SENEGAL,
            self::SERBIA => Numeric::SERBIA,
            self::SEYCHELLES => Numeric::SEYCHELLES,
            self::SIERRA_LEONE => Numeric::SIERRA_LEONE,
            self::SINGAPORE => Numeric::SINGAPORE,
            self::SINT_MAARTEN => Numeric::SINT_MAARTEN,
            self::SLOVAKIA => Numeric::SLOVAKIA,
            self::SLOVENIA => Numeric::SLOVENIA,
            self::SOLOMON_ISLANDS => Numeric::SOLOMON_ISLANDS,
            self::SOMALIA => Numeric::SOMALIA,
            self::SOUTH_AFRICA => Numeric::SOUTH_AFRICA,
            self::SOUTH_GEORGIA_SOUTH_SANDWICH_ISLANDS => Numeric::SOUTH_GEORGIA_SOUTH_SANDWICH_ISLANDS,
            self::SOUTH_KOREA => Numeric::SOUTH_KOREA,
            self::SOUTH_SUDAN => Numeric::SOUTH_SUDAN,
            self::SPAIN => Numeric::SPAIN,
            self::SRI_LANKA => Numeric::SRI_LANKA,
            self::ST_BARTHELEMY => Numeric::ST_BARTHELEMY,
            self::ST_HELENA => Numeric::ST_HELENA,
            self::ST_KITTS_NEVIS => Numeric::ST_KITTS_NEVIS,
            self::ST_LUCIA => Numeric::ST_LUCIA,
            self::ST_MARTIN => Numeric::ST_MARTIN,
            self::ST_PIERRE_MIQUELON => Numeric::ST_PIERRE_MIQUELON,
            self::ST_VINCENT_GRENADINES => Numeric::ST_VINCENT_GRENADINES,
            self::SUDAN => Numeric::SUDAN,
            self::SURINAME => Numeric::SURINAME,
            self::SVALBARD_JAN_MAYEN => Numeric::SVALBARD_JAN_MAYEN,
            self::SWEDEN => Numeric::SWEDEN,
            self::SWITZERLAND => Numeric::SWITZERLAND,
            self::SYRIA => Numeric::SYRIA,
            self::TAIWAN => Numeric::TAIWAN,
            self::TAJIKISTAN => Numeric::TAJIKISTAN,
            self::TANZANIA => Numeric::TANZANIA,
            self::THAILAND => Numeric::THAILAND,
            self::TIMOR_LESTE => Numeric::TIMOR_LESTE,
            self::TOGO => Numeric::TOGO,
            self::TOKELAU => Numeric::TOKELAU,
            self::TONGA => Numeric::TONGA,
            self::TRINIDAD_TOBAGO => Numeric::TRINIDAD_TOBAGO,
            self::TUNISIA => Numeric::TUNISIA,
            self::TURKEY => Numeric::TURKEY,
            self::TURKMENISTAN => Numeric::TURKMENISTAN,
            self::TURKS_CAICOS_ISLANDS => Numeric::TURKS_CAICOS_ISLANDS,
            self::TUVALU => Numeric::TUVALU,
            self::U_S_OUTLYING_ISLANDS => Numeric::U_S_OUTLYING_ISLANDS,
            self::U_S_VIRGIN_ISLANDS => Numeric::U_S_VIRGIN_ISLANDS,
            self::UGANDA => Numeric::UGANDA,
            self::UKRAINE => Numeric::UKRAINE,
            self::UNITED_ARAB_EMIRATES => Numeric::UNITED_ARAB_EMIRATES,
            self::UNITED_KINGDOM => Numeric::UNITED_KINGDOM,
            self::UNITED_STATES => Numeric::UNITED_STATES,
            self::URUGUAY => Numeric::URUGUAY,
            self::UZBEKISTAN => Numeric::UZBEKISTAN,
            self::VANUATU => Numeric::VANUATU,
            self::VATICAN_CITY => Numeric::VATICAN_CITY,
            self::VENEZUELA => Numeric::VENEZUELA,
            self::VIETNAM => Numeric::VIETNAM,
            self::WALLIS_FUTUNA => Numeric::WALLIS_FUTUNA,
            self::WESTERN_SAHARA => Numeric::WESTERN_SAHARA,
            self::YEMEN => Numeric::YEMEN,
            self::ZAMBIA => Numeric::ZAMBIA,
            self::ZIMBABWE => Numeric::ZIMBABWE
        };
    }

    public function asAlpha2(): Alpha2
    {
        return $this;
    }

}
