<?php

/** @noinspection SpellCheckingInspection */

namespace Tactics\ISO3166\Enum\ISO3166_1;

use Tactics\ISO3166\CountryCode;

enum Alpha3: string implements CountryCode
{
    case AFGHANISTAN = 'AFG';
    case AALAND_ISLANDS = 'ALA';
    case ALBANIA = 'ALB';
    case ALGERIA = 'DZA';
    case AMERICAN_SAMOA = 'ASM';
    case ANDORRA = 'AND';
    case ANGOLA = 'AGO';
    case ANGUILLA = 'AIA';
    case ANTARCTICA = 'ATA';
    case ANTIGUA_BARBUDA = 'ATG';
    case ARGENTINA = 'ARG';
    case ARMENIA = 'ARM';
    case ARUBA = 'ABW';
    case AUSTRALIA = 'AUS';
    case AUSTRIA = 'AUT';
    case AZERBAIJAN = 'AZE';
    case BAHAMAS = 'BHS';
    case BAHRAIN = 'BHR';
    case BANGLADESH = 'BGD';
    case BARBADOS = 'BRB';
    case BELARUS = 'BLR';
    case BELGIUM = 'BEL';
    case BELIZE = 'BLZ';
    case BENIN = 'BEN';
    case BERMUDA = 'BMU';
    case BHUTAN = 'BTN';
    case BOLIVIA = 'BOL';
    case BOSNIA_HERZEGOVINA = 'BIH';
    case BOTSWANA = 'BWA';
    case BOUVET_ISLAND = 'BVT';
    case BRAZIL = 'BRA';
    case BRITISH_INDIAN_OCEAN_TERRITORY = 'IOT';
    case BRITISH_VIRGIN_ISLANDS = 'VGB';
    case BRUNEI = 'BRN';
    case BULGARIA = 'BGR';
    case BURKINA_FASO = 'BFA';
    case BURUNDI = 'BDI';
    case CAMBODIA = 'KHM';
    case CAMEROON = 'CMR';
    case CANADA = 'CAN';
    case CAPE_VERDE = 'CPV';
    case CARIBBEAN_NETHERLANDS = 'BES';
    case CAYMAN_ISLANDS = 'CYM';
    case CENTRAL_AFRICAN_REPUBLIC = 'CAF';
    case CHAD = 'TCD';
    case CHILE = 'CHL';
    case CHINA = 'CHN';
    case CHRISTMAS_ISLAND = 'CXR';
    case COCOS_KEELING_ISLANDS = 'CCK';
    case COLOMBIA = 'COL';
    case COMOROS = 'COM';
    case CONGO_BRAZZAVILLE = 'COG';
    case CONGO_KINSHASA = 'COD';
    case COOK_ISLANDS = 'COK';
    case COSTA_RICA = 'CRI';
    case COTE_D_IVOIRE = 'CIV';
    case CROATIA = 'HRV';
    case CUBA = 'CUB';
    case CURACAO = 'CUW';
    case CYPRUS = 'CYP';
    case CZECHIA = 'CZE';
    case DENMARK = 'DNK';
    case DJIBOUTI = 'DJI';
    case DOMINICA = 'DMA';
    case DOMINICAN_REPUBLIC = 'DOM';
    case ECUADOR = 'ECU';
    case EGYPT = 'EGY';
    case EL_SALVADOR = 'SLV';
    case EQUATORIAL_GUINEA = 'GNQ';
    case ERITREA = 'ERI';
    case ESTONIA = 'EST';
    case ESWATINI = 'SWZ';
    case ETHIOPIA = 'ETH';
    case FALKLAND_ISLANDS = 'FLK';
    case FAROE_ISLANDS = 'FRO';
    case FIJI = 'FJI';
    case FINLAND = 'FIN';
    case FRANCE = 'FRA';
    case FRENCH_GUIANA = 'GUF';
    case FRENCH_POLYNESIA = 'PYF';
    case FRENCH_SOUTHERN_TERRITORIES = 'ATF';
    case GABON = 'GAB';
    case GAMBIA = 'GMB';
    case GEORGIA = 'GEO';
    case GERMANY = 'DEU';
    case GHANA = 'GHA';
    case GIBRALTAR = 'GIB';
    case GREECE = 'GRC';
    case GREENLAND = 'GRL';
    case GRENADA = 'GRD';
    case GUADELOUPE = 'GLP';
    case GUAM = 'GUM';
    case GUATEMALA = 'GTM';
    case GUERNSEY = 'GGY';
    case GUINEA = 'GIN';
    case GUINEA_BISSAU = 'GNB';
    case GUYANA = 'GUY';
    case HAITI = 'HTI';
    case HEARD_MCDONALD_ISLANDS = 'HMD';
    case HONDURAS = 'HND';
    case HONG_KONG_SAR_CHINA = 'HKG';
    case HUNGARY = 'HUN';
    case ICELAND = 'ISL';
    case INDIA = 'IND';
    case INDONESIA = 'IDN';
    case IRAN = 'IRN';
    case IRAQ = 'IRQ';
    case IRELAND = 'IRL';
    case ISLE_OF_MAN = 'IMN';
    case ISRAEL = 'ISR';
    case ITALY = 'ITA';
    case JAMAICA = 'JAM';
    case JAPAN = 'JPN';
    case JERSEY = 'JEY';
    case JORDAN = 'JOR';
    case KAZAKHSTAN = 'KAZ';
    case KENYA = 'KEN';
    case KIRIBATI = 'KIR';
    case KUWAIT = 'KWT';
    case KYRGYZSTAN = 'KGZ';
    case LAOS = 'LAO';
    case LATVIA = 'LVA';
    case LEBANON = 'LBN';
    case LESOTHO = 'LSO';
    case LIBERIA = 'LBR';
    case LIBYA = 'LBY';
    case LIECHTENSTEIN = 'LIE';
    case LITHUANIA = 'LTU';
    case LUXEMBOURG = 'LUX';
    case MACAO_SAR_CHINA = 'MAC';
    case MADAGASCAR = 'MDG';
    case MALAWI = 'MWI';
    case MALAYSIA = 'MYS';
    case MALDIVES = 'MDV';
    case MALI = 'MLI';
    case MALTA = 'MLT';
    case MARSHALL_ISLANDS = 'MHL';
    case MARTINIQUE = 'MTQ';
    case MAURITANIA = 'MRT';
    case MAURITIUS = 'MUS';
    case MAYOTTE = 'MYT';
    case MEXICO = 'MEX';
    case MICRONESIA = 'FSM';
    case MOLDOVA = 'MDA';
    case MONACO = 'MCO';
    case MONGOLIA = 'MNG';
    case MONTENEGRO = 'MNE';
    case MONTSERRAT = 'MSR';
    case MOROCCO = 'MAR';
    case MOZAMBIQUE = 'MOZ';
    case MYANMAR_BURMA = 'MMR';
    case NAMIBIA = 'NAM';
    case NAURU = 'NRU';
    case NEPAL = 'NPL';
    case NETHERLANDS = 'NLD';
    case NEW_CALEDONIA = 'NCL';
    case NEW_ZEALAND = 'NZL';
    case NICARAGUA = 'NIC';
    case NIGER = 'NER';
    case NIGERIA = 'NGA';
    case NIUE = 'NIU';
    case NORFOLK_ISLAND = 'NFK';
    case NORTH_KOREA = 'PRK';
    case NORTH_MACEDONIA = 'MKD';
    case NORTHERN_MARIANA_ISLANDS = 'MNP';
    case NORWAY = 'NOR';
    case OMAN = 'OMN';
    case PAKISTAN = 'PAK';
    case PALAU = 'PLW';
    case PALESTINIAN_TERRITORIES = 'PSE';
    case PANAMA = 'PAN';
    case PAPUA_NEW_GUINEA = 'PNG';
    case PARAGUAY = 'PRY';
    case PERU = 'PER';
    case PHILIPPINES = 'PHL';
    case PITCAIRN_ISLANDS = 'PCN';
    case POLAND = 'POL';
    case PORTUGAL = 'PRT';
    case PUERTO_RICO = 'PRI';
    case QATAR = 'QAT';
    case REUNION = 'REU';
    case ROMANIA = 'ROU';
    case RUSSIA = 'RUS';
    case RWANDA = 'RWA';
    case SAMOA = 'WSM';
    case SAN_MARINO = 'SMR';
    case SAO_TOME_PRINCIPE = 'STP';
    case SAUDI_ARABIA = 'SAU';
    case SENEGAL = 'SEN';
    case SERBIA = 'SRB';
    case SEYCHELLES = 'SYC';
    case SIERRA_LEONE = 'SLE';
    case SINGAPORE = 'SGP';
    case SINT_MAARTEN = 'SXM';
    case SLOVAKIA = 'SVK';
    case SLOVENIA = 'SVN';
    case SOLOMON_ISLANDS = 'SLB';
    case SOMALIA = 'SOM';
    case SOUTH_AFRICA = 'ZAF';
    case SOUTH_GEORGIA_SOUTH_SANDWICH_ISLANDS = 'SGS';
    case SOUTH_KOREA = 'KOR';
    case SOUTH_SUDAN = 'SSD';
    case SPAIN = 'ESP';
    case SRI_LANKA = 'LKA';
    case ST_BARTHELEMY = 'BLM';
    case ST_HELENA = 'SHN';
    case ST_KITTS_NEVIS = 'KNA';
    case ST_LUCIA = 'LCA';
    case ST_MARTIN = 'MAF';
    case ST_PIERRE_MIQUELON = 'SPM';
    case ST_VINCENT_GRENADINES = 'VCT';
    case SUDAN = 'SDN';
    case SURINAME = 'SUR';
    case SVALBARD_JAN_MAYEN = 'SJM';
    case SWEDEN = 'SWE';
    case SWITZERLAND = 'CHE';
    case SYRIA = 'SYR';
    case TAIWAN = 'TWN';
    case TAJIKISTAN = 'TJK';
    case TANZANIA = 'TZA';
    case THAILAND = 'THA';
    case TIMOR_LESTE = 'TLS';
    case TOGO = 'TGO';
    case TOKELAU = 'TKL';
    case TONGA = 'TON';
    case TRINIDAD_TOBAGO = 'TTO';
    case TUNISIA = 'TUN';
    case TURKEY = 'TUR';
    case TURKMENISTAN = 'TKM';
    case TURKS_CAICOS_ISLANDS = 'TCA';
    case TUVALU = 'TUV';
    case U_S_OUTLYING_ISLANDS = 'UMI';
    case U_S_VIRGIN_ISLANDS = 'VIR';
    case UGANDA = 'UGA';
    case UKRAINE = 'UKR';
    case UNITED_ARAB_EMIRATES = 'ARE';
    case UNITED_KINGDOM = 'GBR';
    case UNITED_STATES = 'USA';
    case URUGUAY = 'URY';
    case UZBEKISTAN = 'UZB';
    case VANUATU = 'VUT';
    case VATICAN_CITY = 'VAT';
    case VENEZUELA = 'VEN';
    case VIETNAM = 'VNM';
    case WALLIS_FUTUNA = 'WLF';
    case WESTERN_SAHARA = 'ESH';
    case YEMEN = 'YEM';
    case ZAMBIA = 'ZMB';
    case ZIMBABWE = 'ZWE';


    public function asAlpha2(): Alpha2
    {
        return match ($this) {
            self::AFGHANISTAN => Alpha2::AFGHANISTAN,
            self::AALAND_ISLANDS => Alpha2::AALAND_ISLANDS,
            self::ALBANIA => Alpha2::ALBANIA,
            self::ALGERIA => Alpha2::ALGERIA,
            self::AMERICAN_SAMOA => Alpha2::AMERICAN_SAMOA,
            self::ANDORRA => Alpha2::ANDORRA,
            self::ANGOLA => Alpha2::ANGOLA,
            self::ANGUILLA => Alpha2::ANGUILLA,
            self::ANTARCTICA => Alpha2::ANTARCTICA,
            self::ANTIGUA_BARBUDA => Alpha2::ANTIGUA_BARBUDA,
            self::ARGENTINA => Alpha2::ARGENTINA,
            self::ARMENIA => Alpha2::ARMENIA,
            self::ARUBA => Alpha2::ARUBA,
            self::AUSTRALIA => Alpha2::AUSTRALIA,
            self::AUSTRIA => Alpha2::AUSTRIA,
            self::AZERBAIJAN => Alpha2::AZERBAIJAN,
            self::BAHAMAS => Alpha2::BAHAMAS,
            self::BAHRAIN => Alpha2::BAHRAIN,
            self::BANGLADESH => Alpha2::BANGLADESH,
            self::BARBADOS => Alpha2::BARBADOS,
            self::BELARUS => Alpha2::BELARUS,
            self::BELGIUM => Alpha2::BELGIUM,
            self::BELIZE => Alpha2::BELIZE,
            self::BENIN => Alpha2::BENIN,
            self::BERMUDA => Alpha2::BERMUDA,
            self::BHUTAN => Alpha2::BHUTAN,
            self::BOLIVIA => Alpha2::BOLIVIA,
            self::BOSNIA_HERZEGOVINA => Alpha2::BOSNIA_HERZEGOVINA,
            self::BOTSWANA => Alpha2::BOTSWANA,
            self::BOUVET_ISLAND => Alpha2::BOUVET_ISLAND,
            self::BRAZIL => Alpha2::BRAZIL,
            self::BRITISH_INDIAN_OCEAN_TERRITORY => Alpha2::BRITISH_INDIAN_OCEAN_TERRITORY,
            self::BRITISH_VIRGIN_ISLANDS => Alpha2::BRITISH_VIRGIN_ISLANDS,
            self::BRUNEI => Alpha2::BRUNEI,
            self::BULGARIA => Alpha2::BULGARIA,
            self::BURKINA_FASO => Alpha2::BURKINA_FASO,
            self::BURUNDI => Alpha2::BURUNDI,
            self::CAMBODIA => Alpha2::CAMBODIA,
            self::CAMEROON => Alpha2::CAMEROON,
            self::CANADA => Alpha2::CANADA,
            self::CAPE_VERDE => Alpha2::CAPE_VERDE,
            self::CARIBBEAN_NETHERLANDS => Alpha2::CARIBBEAN_NETHERLANDS,
            self::CAYMAN_ISLANDS => Alpha2::CAYMAN_ISLANDS,
            self::CENTRAL_AFRICAN_REPUBLIC => Alpha2::CENTRAL_AFRICAN_REPUBLIC,
            self::CHAD => Alpha2::CHAD,
            self::CHILE => Alpha2::CHILE,
            self::CHINA => Alpha2::CHINA,
            self::CHRISTMAS_ISLAND => Alpha2::CHRISTMAS_ISLAND,
            self::COCOS_KEELING_ISLANDS => Alpha2::COCOS_KEELING_ISLANDS,
            self::COLOMBIA => Alpha2::COLOMBIA,
            self::COMOROS => Alpha2::COMOROS,
            self::CONGO_BRAZZAVILLE => Alpha2::CONGO_BRAZZAVILLE,
            self::CONGO_KINSHASA => Alpha2::CONGO_KINSHASA,
            self::COOK_ISLANDS => Alpha2::COOK_ISLANDS,
            self::COSTA_RICA => Alpha2::COSTA_RICA,
            self::COTE_D_IVOIRE => Alpha2::COTE_D_IVOIRE,
            self::CROATIA => Alpha2::CROATIA,
            self::CUBA => Alpha2::CUBA,
            self::CURACAO => Alpha2::CURACAO,
            self::CYPRUS => Alpha2::CYPRUS,
            self::CZECHIA => Alpha2::CZECHIA,
            self::DENMARK => Alpha2::DENMARK,
            self::DJIBOUTI => Alpha2::DJIBOUTI,
            self::DOMINICA => Alpha2::DOMINICA,
            self::DOMINICAN_REPUBLIC => Alpha2::DOMINICAN_REPUBLIC,
            self::ECUADOR => Alpha2::ECUADOR,
            self::EGYPT => Alpha2::EGYPT,
            self::EL_SALVADOR => Alpha2::EL_SALVADOR,
            self::EQUATORIAL_GUINEA => Alpha2::EQUATORIAL_GUINEA,
            self::ERITREA => Alpha2::ERITREA,
            self::ESTONIA => Alpha2::ESTONIA,
            self::ESWATINI => Alpha2::ESWATINI,
            self::ETHIOPIA => Alpha2::ETHIOPIA,
            self::FALKLAND_ISLANDS => Alpha2::FALKLAND_ISLANDS,
            self::FAROE_ISLANDS => Alpha2::FAROE_ISLANDS,
            self::FIJI => Alpha2::FIJI,
            self::FINLAND => Alpha2::FINLAND,
            self::FRANCE => Alpha2::FRANCE,
            self::FRENCH_GUIANA => Alpha2::FRENCH_GUIANA,
            self::FRENCH_POLYNESIA => Alpha2::FRENCH_POLYNESIA,
            self::FRENCH_SOUTHERN_TERRITORIES => Alpha2::FRENCH_SOUTHERN_TERRITORIES,
            self::GABON => Alpha2::GABON,
            self::GAMBIA => Alpha2::GAMBIA,
            self::GEORGIA => Alpha2::GEORGIA,
            self::GERMANY => Alpha2::GERMANY,
            self::GHANA => Alpha2::GHANA,
            self::GIBRALTAR => Alpha2::GIBRALTAR,
            self::GREECE => Alpha2::GREECE,
            self::GREENLAND => Alpha2::GREENLAND,
            self::GRENADA => Alpha2::GRENADA,
            self::GUADELOUPE => Alpha2::GUADELOUPE,
            self::GUAM => Alpha2::GUAM,
            self::GUATEMALA => Alpha2::GUATEMALA,
            self::GUERNSEY => Alpha2::GUERNSEY,
            self::GUINEA => Alpha2::GUINEA,
            self::GUINEA_BISSAU => Alpha2::GUINEA_BISSAU,
            self::GUYANA => Alpha2::GUYANA,
            self::HAITI => Alpha2::HAITI,
            self::HEARD_MCDONALD_ISLANDS => Alpha2::HEARD_MCDONALD_ISLANDS,
            self::HONDURAS => Alpha2::HONDURAS,
            self::HONG_KONG_SAR_CHINA => Alpha2::HONG_KONG_SAR_CHINA,
            self::HUNGARY => Alpha2::HUNGARY,
            self::ICELAND => Alpha2::ICELAND,
            self::INDIA => Alpha2::INDIA,
            self::INDONESIA => Alpha2::INDONESIA,
            self::IRAN => Alpha2::IRAN,
            self::IRAQ => Alpha2::IRAQ,
            self::IRELAND => Alpha2::IRELAND,
            self::ISLE_OF_MAN => Alpha2::ISLE_OF_MAN,
            self::ISRAEL => Alpha2::ISRAEL,
            self::ITALY => Alpha2::ITALY,
            self::JAMAICA => Alpha2::JAMAICA,
            self::JAPAN => Alpha2::JAPAN,
            self::JERSEY => Alpha2::JERSEY,
            self::JORDAN => Alpha2::JORDAN,
            self::KAZAKHSTAN => Alpha2::KAZAKHSTAN,
            self::KENYA => Alpha2::KENYA,
            self::KIRIBATI => Alpha2::KIRIBATI,
            self::KUWAIT => Alpha2::KUWAIT,
            self::KYRGYZSTAN => Alpha2::KYRGYZSTAN,
            self::LAOS => Alpha2::LAOS,
            self::LATVIA => Alpha2::LATVIA,
            self::LEBANON => Alpha2::LEBANON,
            self::LESOTHO => Alpha2::LESOTHO,
            self::LIBERIA => Alpha2::LIBERIA,
            self::LIBYA => Alpha2::LIBYA,
            self::LIECHTENSTEIN => Alpha2::LIECHTENSTEIN,
            self::LITHUANIA => Alpha2::LITHUANIA,
            self::LUXEMBOURG => Alpha2::LUXEMBOURG,
            self::MACAO_SAR_CHINA => Alpha2::MACAO_SAR_CHINA,
            self::MADAGASCAR => Alpha2::MADAGASCAR,
            self::MALAWI => Alpha2::MALAWI,
            self::MALAYSIA => Alpha2::MALAYSIA,
            self::MALDIVES => Alpha2::MALDIVES,
            self::MALI => Alpha2::MALI,
            self::MALTA => Alpha2::MALTA,
            self::MARSHALL_ISLANDS => Alpha2::MARSHALL_ISLANDS,
            self::MARTINIQUE => Alpha2::MARTINIQUE,
            self::MAURITANIA => Alpha2::MAURITANIA,
            self::MAURITIUS => Alpha2::MAURITIUS,
            self::MAYOTTE => Alpha2::MAYOTTE,
            self::MEXICO => Alpha2::MEXICO,
            self::MICRONESIA => Alpha2::MICRONESIA,
            self::MOLDOVA => Alpha2::MOLDOVA,
            self::MONACO => Alpha2::MONACO,
            self::MONGOLIA => Alpha2::MONGOLIA,
            self::MONTENEGRO => Alpha2::MONTENEGRO,
            self::MONTSERRAT => Alpha2::MONTSERRAT,
            self::MOROCCO => Alpha2::MOROCCO,
            self::MOZAMBIQUE => Alpha2::MOZAMBIQUE,
            self::MYANMAR_BURMA => Alpha2::MYANMAR_BURMA,
            self::NAMIBIA => Alpha2::NAMIBIA,
            self::NAURU => Alpha2::NAURU,
            self::NEPAL => Alpha2::NEPAL,
            self::NETHERLANDS => Alpha2::NETHERLANDS,
            self::NEW_CALEDONIA => Alpha2::NEW_CALEDONIA,
            self::NEW_ZEALAND => Alpha2::NEW_ZEALAND,
            self::NICARAGUA => Alpha2::NICARAGUA,
            self::NIGER => Alpha2::NIGER,
            self::NIGERIA => Alpha2::NIGERIA,
            self::NIUE => Alpha2::NIUE,
            self::NORFOLK_ISLAND => Alpha2::NORFOLK_ISLAND,
            self::NORTH_KOREA => Alpha2::NORTH_KOREA,
            self::NORTH_MACEDONIA => Alpha2::NORTH_MACEDONIA,
            self::NORTHERN_MARIANA_ISLANDS => Alpha2::NORTHERN_MARIANA_ISLANDS,
            self::NORWAY => Alpha2::NORWAY,
            self::OMAN => Alpha2::OMAN,
            self::PAKISTAN => Alpha2::PAKISTAN,
            self::PALAU => Alpha2::PALAU,
            self::PALESTINIAN_TERRITORIES => Alpha2::PALESTINIAN_TERRITORIES,
            self::PANAMA => Alpha2::PANAMA,
            self::PAPUA_NEW_GUINEA => Alpha2::PAPUA_NEW_GUINEA,
            self::PARAGUAY => Alpha2::PARAGUAY,
            self::PERU => Alpha2::PERU,
            self::PHILIPPINES => Alpha2::PHILIPPINES,
            self::PITCAIRN_ISLANDS => Alpha2::PITCAIRN_ISLANDS,
            self::POLAND => Alpha2::POLAND,
            self::PORTUGAL => Alpha2::PORTUGAL,
            self::PUERTO_RICO => Alpha2::PUERTO_RICO,
            self::QATAR => Alpha2::QATAR,
            self::REUNION => Alpha2::REUNION,
            self::ROMANIA => Alpha2::ROMANIA,
            self::RUSSIA => Alpha2::RUSSIA,
            self::RWANDA => Alpha2::RWANDA,
            self::SAMOA => Alpha2::SAMOA,
            self::SAN_MARINO => Alpha2::SAN_MARINO,
            self::SAO_TOME_PRINCIPE => Alpha2::SAO_TOME_PRINCIPE,
            self::SAUDI_ARABIA => Alpha2::SAUDI_ARABIA,
            self::SENEGAL => Alpha2::SENEGAL,
            self::SERBIA => Alpha2::SERBIA,
            self::SEYCHELLES => Alpha2::SEYCHELLES,
            self::SIERRA_LEONE => Alpha2::SIERRA_LEONE,
            self::SINGAPORE => Alpha2::SINGAPORE,
            self::SINT_MAARTEN => Alpha2::SINT_MAARTEN,
            self::SLOVAKIA => Alpha2::SLOVAKIA,
            self::SLOVENIA => Alpha2::SLOVENIA,
            self::SOLOMON_ISLANDS => Alpha2::SOLOMON_ISLANDS,
            self::SOMALIA => Alpha2::SOMALIA,
            self::SOUTH_AFRICA => Alpha2::SOUTH_AFRICA,
            self::SOUTH_GEORGIA_SOUTH_SANDWICH_ISLANDS => Alpha2::SOUTH_GEORGIA_SOUTH_SANDWICH_ISLANDS,
            self::SOUTH_KOREA => Alpha2::SOUTH_KOREA,
            self::SOUTH_SUDAN => Alpha2::SOUTH_SUDAN,
            self::SPAIN => Alpha2::SPAIN,
            self::SRI_LANKA => Alpha2::SRI_LANKA,
            self::ST_BARTHELEMY => Alpha2::ST_BARTHELEMY,
            self::ST_HELENA => Alpha2::ST_HELENA,
            self::ST_KITTS_NEVIS => Alpha2::ST_KITTS_NEVIS,
            self::ST_LUCIA => Alpha2::ST_LUCIA,
            self::ST_MARTIN => Alpha2::ST_MARTIN,
            self::ST_PIERRE_MIQUELON => Alpha2::ST_PIERRE_MIQUELON,
            self::ST_VINCENT_GRENADINES => Alpha2::ST_VINCENT_GRENADINES,
            self::SUDAN => Alpha2::SUDAN,
            self::SURINAME => Alpha2::SURINAME,
            self::SVALBARD_JAN_MAYEN => Alpha2::SVALBARD_JAN_MAYEN,
            self::SWEDEN => Alpha2::SWEDEN,
            self::SWITZERLAND => Alpha2::SWITZERLAND,
            self::SYRIA => Alpha2::SYRIA,
            self::TAIWAN => Alpha2::TAIWAN,
            self::TAJIKISTAN => Alpha2::TAJIKISTAN,
            self::TANZANIA => Alpha2::TANZANIA,
            self::THAILAND => Alpha2::THAILAND,
            self::TIMOR_LESTE => Alpha2::TIMOR_LESTE,
            self::TOGO => Alpha2::TOGO,
            self::TOKELAU => Alpha2::TOKELAU,
            self::TONGA => Alpha2::TONGA,
            self::TRINIDAD_TOBAGO => Alpha2::TRINIDAD_TOBAGO,
            self::TUNISIA => Alpha2::TUNISIA,
            self::TURKEY => Alpha2::TURKEY,
            self::TURKMENISTAN => Alpha2::TURKMENISTAN,
            self::TURKS_CAICOS_ISLANDS => Alpha2::TURKS_CAICOS_ISLANDS,
            self::TUVALU => Alpha2::TUVALU,
            self::U_S_OUTLYING_ISLANDS => Alpha2::U_S_OUTLYING_ISLANDS,
            self::U_S_VIRGIN_ISLANDS => Alpha2::U_S_VIRGIN_ISLANDS,
            self::UGANDA => Alpha2::UGANDA,
            self::UKRAINE => Alpha2::UKRAINE,
            self::UNITED_ARAB_EMIRATES => Alpha2::UNITED_ARAB_EMIRATES,
            self::UNITED_KINGDOM => Alpha2::UNITED_KINGDOM,
            self::UNITED_STATES => Alpha2::UNITED_STATES,
            self::URUGUAY => Alpha2::URUGUAY,
            self::UZBEKISTAN => Alpha2::UZBEKISTAN,
            self::VANUATU => Alpha2::VANUATU,
            self::VATICAN_CITY => Alpha2::VATICAN_CITY,
            self::VENEZUELA => Alpha2::VENEZUELA,
            self::VIETNAM => Alpha2::VIETNAM,
            self::WALLIS_FUTUNA => Alpha2::WALLIS_FUTUNA,
            self::WESTERN_SAHARA => Alpha2::WESTERN_SAHARA,
            self::YEMEN => Alpha2::YEMEN,
            self::ZAMBIA => Alpha2::ZAMBIA,
            self::ZIMBABWE => Alpha2::ZIMBABWE
        };
    }

    public function asAlpha3(): Alpha3
    {
        return $this;
    }

    public function asNumeric(): Numeric
    {
        return match ($this) {
            self::AFGHANISTAN => Numeric::AFGHANISTAN,
            self::AALAND_ISLANDS => Numeric::AALAND_ISLANDS,
            self::ALBANIA => Numeric::ALBANIA,
            self::ALGERIA => Numeric::ALGERIA,
            self::AMERICAN_SAMOA => Numeric::AMERICAN_SAMOA,
            self::ANDORRA => Numeric::ANDORRA,
            self::ANGOLA => Numeric::ANGOLA,
            self::ANGUILLA => Numeric::ANGUILLA,
            self::ANTARCTICA => Numeric::ANTARCTICA,
            self::ANTIGUA_BARBUDA => Numeric::ANTIGUA_BARBUDA,
            self::ARGENTINA => Numeric::ARGENTINA,
            self::ARMENIA => Numeric::ARMENIA,
            self::ARUBA => Numeric::ARUBA,
            self::AUSTRALIA => Numeric::AUSTRALIA,
            self::AUSTRIA => Numeric::AUSTRIA,
            self::AZERBAIJAN => Numeric::AZERBAIJAN,
            self::BAHAMAS => Numeric::BAHAMAS,
            self::BAHRAIN => Numeric::BAHRAIN,
            self::BANGLADESH => Numeric::BANGLADESH,
            self::BARBADOS => Numeric::BARBADOS,
            self::BELARUS => Numeric::BELARUS,
            self::BELGIUM => Numeric::BELGIUM,
            self::BELIZE => Numeric::BELIZE,
            self::BENIN => Numeric::BENIN,
            self::BERMUDA => Numeric::BERMUDA,
            self::BHUTAN => Numeric::BHUTAN,
            self::BOLIVIA => Numeric::BOLIVIA,
            self::BOSNIA_HERZEGOVINA => Numeric::BOSNIA_HERZEGOVINA,
            self::BOTSWANA => Numeric::BOTSWANA,
            self::BOUVET_ISLAND => Numeric::BOUVET_ISLAND,
            self::BRAZIL => Numeric::BRAZIL,
            self::BRITISH_INDIAN_OCEAN_TERRITORY => Numeric::BRITISH_INDIAN_OCEAN_TERRITORY,
            self::BRITISH_VIRGIN_ISLANDS => Numeric::BRITISH_VIRGIN_ISLANDS,
            self::BRUNEI => Numeric::BRUNEI,
            self::BULGARIA => Numeric::BULGARIA,
            self::BURKINA_FASO => Numeric::BURKINA_FASO,
            self::BURUNDI => Numeric::BURUNDI,
            self::CAMBODIA => Numeric::CAMBODIA,
            self::CAMEROON => Numeric::CAMEROON,
            self::CANADA => Numeric::CANADA,
            self::CAPE_VERDE => Numeric::CAPE_VERDE,
            self::CARIBBEAN_NETHERLANDS => Numeric::CARIBBEAN_NETHERLANDS,
            self::CAYMAN_ISLANDS => Numeric::CAYMAN_ISLANDS,
            self::CENTRAL_AFRICAN_REPUBLIC => Numeric::CENTRAL_AFRICAN_REPUBLIC,
            self::CHAD => Numeric::CHAD,
            self::CHILE => Numeric::CHILE,
            self::CHINA => Numeric::CHINA,
            self::CHRISTMAS_ISLAND => Numeric::CHRISTMAS_ISLAND,
            self::COCOS_KEELING_ISLANDS => Numeric::COCOS_KEELING_ISLANDS,
            self::COLOMBIA => Numeric::COLOMBIA,
            self::COMOROS => Numeric::COMOROS,
            self::CONGO_BRAZZAVILLE => Numeric::CONGO_BRAZZAVILLE,
            self::CONGO_KINSHASA => Numeric::CONGO_KINSHASA,
            self::COOK_ISLANDS => Numeric::COOK_ISLANDS,
            self::COSTA_RICA => Numeric::COSTA_RICA,
            self::COTE_D_IVOIRE => Numeric::COTE_D_IVOIRE,
            self::CROATIA => Numeric::CROATIA,
            self::CUBA => Numeric::CUBA,
            self::CURACAO => Numeric::CURACAO,
            self::CYPRUS => Numeric::CYPRUS,
            self::CZECHIA => Numeric::CZECHIA,
            self::DENMARK => Numeric::DENMARK,
            self::DJIBOUTI => Numeric::DJIBOUTI,
            self::DOMINICA => Numeric::DOMINICA,
            self::DOMINICAN_REPUBLIC => Numeric::DOMINICAN_REPUBLIC,
            self::ECUADOR => Numeric::ECUADOR,
            self::EGYPT => Numeric::EGYPT,
            self::EL_SALVADOR => Numeric::EL_SALVADOR,
            self::EQUATORIAL_GUINEA => Numeric::EQUATORIAL_GUINEA,
            self::ERITREA => Numeric::ERITREA,
            self::ESTONIA => Numeric::ESTONIA,
            self::ESWATINI => Numeric::ESWATINI,
            self::ETHIOPIA => Numeric::ETHIOPIA,
            self::FALKLAND_ISLANDS => Numeric::FALKLAND_ISLANDS,
            self::FAROE_ISLANDS => Numeric::FAROE_ISLANDS,
            self::FIJI => Numeric::FIJI,
            self::FINLAND => Numeric::FINLAND,
            self::FRANCE => Numeric::FRANCE,
            self::FRENCH_GUIANA => Numeric::FRENCH_GUIANA,
            self::FRENCH_POLYNESIA => Numeric::FRENCH_POLYNESIA,
            self::FRENCH_SOUTHERN_TERRITORIES => Numeric::FRENCH_SOUTHERN_TERRITORIES,
            self::GABON => Numeric::GABON,
            self::GAMBIA => Numeric::GAMBIA,
            self::GEORGIA => Numeric::GEORGIA,
            self::GERMANY => Numeric::GERMANY,
            self::GHANA => Numeric::GHANA,
            self::GIBRALTAR => Numeric::GIBRALTAR,
            self::GREECE => Numeric::GREECE,
            self::GREENLAND => Numeric::GREENLAND,
            self::GRENADA => Numeric::GRENADA,
            self::GUADELOUPE => Numeric::GUADELOUPE,
            self::GUAM => Numeric::GUAM,
            self::GUATEMALA => Numeric::GUATEMALA,
            self::GUERNSEY => Numeric::GUERNSEY,
            self::GUINEA => Numeric::GUINEA,
            self::GUINEA_BISSAU => Numeric::GUINEA_BISSAU,
            self::GUYANA => Numeric::GUYANA,
            self::HAITI => Numeric::HAITI,
            self::HEARD_MCDONALD_ISLANDS => Numeric::HEARD_MCDONALD_ISLANDS,
            self::HONDURAS => Numeric::HONDURAS,
            self::HONG_KONG_SAR_CHINA => Numeric::HONG_KONG_SAR_CHINA,
            self::HUNGARY => Numeric::HUNGARY,
            self::ICELAND => Numeric::ICELAND,
            self::INDIA => Numeric::INDIA,
            self::INDONESIA => Numeric::INDONESIA,
            self::IRAN => Numeric::IRAN,
            self::IRAQ => Numeric::IRAQ,
            self::IRELAND => Numeric::IRELAND,
            self::ISLE_OF_MAN => Numeric::ISLE_OF_MAN,
            self::ISRAEL => Numeric::ISRAEL,
            self::ITALY => Numeric::ITALY,
            self::JAMAICA => Numeric::JAMAICA,
            self::JAPAN => Numeric::JAPAN,
            self::JERSEY => Numeric::JERSEY,
            self::JORDAN => Numeric::JORDAN,
            self::KAZAKHSTAN => Numeric::KAZAKHSTAN,
            self::KENYA => Numeric::KENYA,
            self::KIRIBATI => Numeric::KIRIBATI,
            self::KUWAIT => Numeric::KUWAIT,
            self::KYRGYZSTAN => Numeric::KYRGYZSTAN,
            self::LAOS => Numeric::LAOS,
            self::LATVIA => Numeric::LATVIA,
            self::LEBANON => Numeric::LEBANON,
            self::LESOTHO => Numeric::LESOTHO,
            self::LIBERIA => Numeric::LIBERIA,
            self::LIBYA => Numeric::LIBYA,
            self::LIECHTENSTEIN => Numeric::LIECHTENSTEIN,
            self::LITHUANIA => Numeric::LITHUANIA,
            self::LUXEMBOURG => Numeric::LUXEMBOURG,
            self::MACAO_SAR_CHINA => Numeric::MACAO_SAR_CHINA,
            self::MADAGASCAR => Numeric::MADAGASCAR,
            self::MALAWI => Numeric::MALAWI,
            self::MALAYSIA => Numeric::MALAYSIA,
            self::MALDIVES => Numeric::MALDIVES,
            self::MALI => Numeric::MALI,
            self::MALTA => Numeric::MALTA,
            self::MARSHALL_ISLANDS => Numeric::MARSHALL_ISLANDS,
            self::MARTINIQUE => Numeric::MARTINIQUE,
            self::MAURITANIA => Numeric::MAURITANIA,
            self::MAURITIUS => Numeric::MAURITIUS,
            self::MAYOTTE => Numeric::MAYOTTE,
            self::MEXICO => Numeric::MEXICO,
            self::MICRONESIA => Numeric::MICRONESIA,
            self::MOLDOVA => Numeric::MOLDOVA,
            self::MONACO => Numeric::MONACO,
            self::MONGOLIA => Numeric::MONGOLIA,
            self::MONTENEGRO => Numeric::MONTENEGRO,
            self::MONTSERRAT => Numeric::MONTSERRAT,
            self::MOROCCO => Numeric::MOROCCO,
            self::MOZAMBIQUE => Numeric::MOZAMBIQUE,
            self::MYANMAR_BURMA => Numeric::MYANMAR_BURMA,
            self::NAMIBIA => Numeric::NAMIBIA,
            self::NAURU => Numeric::NAURU,
            self::NEPAL => Numeric::NEPAL,
            self::NETHERLANDS => Numeric::NETHERLANDS,
            self::NEW_CALEDONIA => Numeric::NEW_CALEDONIA,
            self::NEW_ZEALAND => Numeric::NEW_ZEALAND,
            self::NICARAGUA => Numeric::NICARAGUA,
            self::NIGER => Numeric::NIGER,
            self::NIGERIA => Numeric::NIGERIA,
            self::NIUE => Numeric::NIUE,
            self::NORFOLK_ISLAND => Numeric::NORFOLK_ISLAND,
            self::NORTH_KOREA => Numeric::NORTH_KOREA,
            self::NORTH_MACEDONIA => Numeric::NORTH_MACEDONIA,
            self::NORTHERN_MARIANA_ISLANDS => Numeric::NORTHERN_MARIANA_ISLANDS,
            self::NORWAY => Numeric::NORWAY,
            self::OMAN => Numeric::OMAN,
            self::PAKISTAN => Numeric::PAKISTAN,
            self::PALAU => Numeric::PALAU,
            self::PALESTINIAN_TERRITORIES => Numeric::PALESTINIAN_TERRITORIES,
            self::PANAMA => Numeric::PANAMA,
            self::PAPUA_NEW_GUINEA => Numeric::PAPUA_NEW_GUINEA,
            self::PARAGUAY => Numeric::PARAGUAY,
            self::PERU => Numeric::PERU,
            self::PHILIPPINES => Numeric::PHILIPPINES,
            self::PITCAIRN_ISLANDS => Numeric::PITCAIRN_ISLANDS,
            self::POLAND => Numeric::POLAND,
            self::PORTUGAL => Numeric::PORTUGAL,
            self::PUERTO_RICO => Numeric::PUERTO_RICO,
            self::QATAR => Numeric::QATAR,
            self::REUNION => Numeric::REUNION,
            self::ROMANIA => Numeric::ROMANIA,
            self::RUSSIA => Numeric::RUSSIA,
            self::RWANDA => Numeric::RWANDA,
            self::SAMOA => Numeric::SAMOA,
            self::SAN_MARINO => Numeric::SAN_MARINO,
            self::SAO_TOME_PRINCIPE => Numeric::SAO_TOME_PRINCIPE,
            self::SAUDI_ARABIA => Numeric::SAUDI_ARABIA,
            self::SENEGAL => Numeric::SENEGAL,
            self::SERBIA => Numeric::SERBIA,
            self::SEYCHELLES => Numeric::SEYCHELLES,
            self::SIERRA_LEONE => Numeric::SIERRA_LEONE,
            self::SINGAPORE => Numeric::SINGAPORE,
            self::SINT_MAARTEN => Numeric::SINT_MAARTEN,
            self::SLOVAKIA => Numeric::SLOVAKIA,
            self::SLOVENIA => Numeric::SLOVENIA,
            self::SOLOMON_ISLANDS => Numeric::SOLOMON_ISLANDS,
            self::SOMALIA => Numeric::SOMALIA,
            self::SOUTH_AFRICA => Numeric::SOUTH_AFRICA,
            self::SOUTH_GEORGIA_SOUTH_SANDWICH_ISLANDS => Numeric::SOUTH_GEORGIA_SOUTH_SANDWICH_ISLANDS,
            self::SOUTH_KOREA => Numeric::SOUTH_KOREA,
            self::SOUTH_SUDAN => Numeric::SOUTH_SUDAN,
            self::SPAIN => Numeric::SPAIN,
            self::SRI_LANKA => Numeric::SRI_LANKA,
            self::ST_BARTHELEMY => Numeric::ST_BARTHELEMY,
            self::ST_HELENA => Numeric::ST_HELENA,
            self::ST_KITTS_NEVIS => Numeric::ST_KITTS_NEVIS,
            self::ST_LUCIA => Numeric::ST_LUCIA,
            self::ST_MARTIN => Numeric::ST_MARTIN,
            self::ST_PIERRE_MIQUELON => Numeric::ST_PIERRE_MIQUELON,
            self::ST_VINCENT_GRENADINES => Numeric::ST_VINCENT_GRENADINES,
            self::SUDAN => Numeric::SUDAN,
            self::SURINAME => Numeric::SURINAME,
            self::SVALBARD_JAN_MAYEN => Numeric::SVALBARD_JAN_MAYEN,
            self::SWEDEN => Numeric::SWEDEN,
            self::SWITZERLAND => Numeric::SWITZERLAND,
            self::SYRIA => Numeric::SYRIA,
            self::TAIWAN => Numeric::TAIWAN,
            self::TAJIKISTAN => Numeric::TAJIKISTAN,
            self::TANZANIA => Numeric::TANZANIA,
            self::THAILAND => Numeric::THAILAND,
            self::TIMOR_LESTE => Numeric::TIMOR_LESTE,
            self::TOGO => Numeric::TOGO,
            self::TOKELAU => Numeric::TOKELAU,
            self::TONGA => Numeric::TONGA,
            self::TRINIDAD_TOBAGO => Numeric::TRINIDAD_TOBAGO,
            self::TUNISIA => Numeric::TUNISIA,
            self::TURKEY => Numeric::TURKEY,
            self::TURKMENISTAN => Numeric::TURKMENISTAN,
            self::TURKS_CAICOS_ISLANDS => Numeric::TURKS_CAICOS_ISLANDS,
            self::TUVALU => Numeric::TUVALU,
            self::U_S_OUTLYING_ISLANDS => Numeric::U_S_OUTLYING_ISLANDS,
            self::U_S_VIRGIN_ISLANDS => Numeric::U_S_VIRGIN_ISLANDS,
            self::UGANDA => Numeric::UGANDA,
            self::UKRAINE => Numeric::UKRAINE,
            self::UNITED_ARAB_EMIRATES => Numeric::UNITED_ARAB_EMIRATES,
            self::UNITED_KINGDOM => Numeric::UNITED_KINGDOM,
            self::UNITED_STATES => Numeric::UNITED_STATES,
            self::URUGUAY => Numeric::URUGUAY,
            self::UZBEKISTAN => Numeric::UZBEKISTAN,
            self::VANUATU => Numeric::VANUATU,
            self::VATICAN_CITY => Numeric::VATICAN_CITY,
            self::VENEZUELA => Numeric::VENEZUELA,
            self::VIETNAM => Numeric::VIETNAM,
            self::WALLIS_FUTUNA => Numeric::WALLIS_FUTUNA,
            self::WESTERN_SAHARA => Numeric::WESTERN_SAHARA,
            self::YEMEN => Numeric::YEMEN,
            self::ZAMBIA => Numeric::ZAMBIA,
            self::ZIMBABWE => Numeric::ZIMBABWE
        };
    }
}
