<?php /** @noinspection SpellCheckingInspection */

namespace Tactics\ISO3166\Enum\ISO3166_1;

use Tactics\ISO3166\CountryCode;

enum Numeric : string implements CountryCode
{
    case AFGHANISTAN = '004';
    case AALAND_ISLANDS = '248';
    case ALBANIA = '008';
    case ALGERIA = '012';
    case AMERICAN_SAMOA = '016';
    case ANDORRA = '020';
    case ANGOLA = '024';
    case ANGUILLA = '660';
    case ANTARCTICA = '010';
    case ANTIGUA_BARBUDA = '028';
    case ARGENTINA = '032';
    case ARMENIA = '051';
    case ARUBA = '533';
    case AUSTRALIA = '036';
    case AUSTRIA = '040';
    case AZERBAIJAN = '031';
    case BAHAMAS = '044';
    case BAHRAIN = '048';
    case BANGLADESH = '050';
    case BARBADOS = '052';
    case BELARUS = '112';
    case BELGIUM = '056';
    case BELIZE = '084';
    case BENIN = '204';
    case BERMUDA = '060';
    case BHUTAN = '064';
    case BOLIVIA = '068';
    case BOSNIA_HERZEGOVINA = '070';
    case BOTSWANA = '072';
    case BOUVET_ISLAND = '074';
    case BRAZIL = '076';
    case BRITISH_INDIAN_OCEAN_TERRITORY = '086';
    case BRITISH_VIRGIN_ISLANDS = '092';
    case BRUNEI = '096';
    case BULGARIA = '100';
    case BURKINA_FASO = '854';
    case BURUNDI = '108';
    case CAMBODIA = '116';
    case CAMEROON = '120';
    case CANADA = '124';
    case CAPE_VERDE = '132';
    case CARIBBEAN_NETHERLANDS = '535';
    case CAYMAN_ISLANDS = '136';
    case CENTRAL_AFRICAN_REPUBLIC = '140';
    case CHAD = '148';
    case CHILE = '152';
    case CHINA = '156';
    case CHRISTMAS_ISLAND = '162';
    case COCOS_KEELING_ISLANDS = '166';
    case COLOMBIA = '170';
    case COMOROS = '174';
    case CONGO_BRAZZAVILLE = '178';
    case CONGO_KINSHASA = '180';
    case COOK_ISLANDS = '184';
    case COSTA_RICA = '188';
    case COTE_D_IVOIRE = '384';
    case CROATIA = '191';
    case CUBA = '192';
    case CURACAO = '531';
    case CYPRUS = '196';
    case CZECHIA = '203';
    case DENMARK = '208';
    case DJIBOUTI = '262';
    case DOMINICA = '212';
    case DOMINICAN_REPUBLIC = '214';
    case ECUADOR = '218';
    case EGYPT = '818';
    case EL_SALVADOR = '222';
    case EQUATORIAL_GUINEA = '226';
    case ERITREA = '232';
    case ESTONIA = '233';
    case ESWATINI = '748';

    case ETHIOPIA = '231';
    case FALKLAND_ISLANDS = '238';
    case FAROE_ISLANDS = '234';
    case FIJI = '242';
    case FINLAND = '246';
    case FRANCE = '250';
    case FRENCH_GUIANA = '254';
    case FRENCH_POLYNESIA = '258';
    case FRENCH_SOUTHERN_TERRITORIES = '260';
    case GABON = '266';
    case GAMBIA = '270';
    case GEORGIA = '268';
    case GERMANY = '276';
    case GHANA = '288';
    case GIBRALTAR = '292';
    case GREECE = '300';
    case GREENLAND = '304';
    case GRENADA = '308';
    case GUADELOUPE = '312';
    case GUAM = '316';
    case GUATEMALA = '320';
    case GUERNSEY = '831';
    case GUINEA = '324';
    case GUINEA_BISSAU = '624';
    case GUYANA = '328';
    case HAITI = '332';
    case HEARD_MCDONALD_ISLANDS = '334';
    case HONDURAS = '340';
    case HONG_KONG_SAR_CHINA = '344';
    case HUNGARY = '348';
    case ICELAND = '352';
    case INDIA = '356';
    case INDONESIA = '360';
    case IRAN = '364';
    case IRAQ = '368';
    case IRELAND = '372';
    case ISLE_OF_MAN = '833';
    case ISRAEL = '376';
    case ITALY = '380';
    case JAMAICA = '388';
    case JAPAN = '392';
    case JERSEY = '832';
    case JORDAN = '400';
    case KAZAKHSTAN = '398';
    case KENYA = '404';
    case KIRIBATI = '296';
    case KUWAIT = '414';
    case KYRGYZSTAN = '417';
    case LAOS = '418';
    case LATVIA = '428';
    case LEBANON = '422';
    case LESOTHO = '426';
    case LIBERIA = '430';
    case LIBYA = '434';
    case LIECHTENSTEIN = '438';
    case LITHUANIA = '440';
    case LUXEMBOURG = '442';
    case MACAO_SAR_CHINA = '446';
    case MADAGASCAR = '450';
    case MALAWI = '454';
    case MALAYSIA = '458';
    case MALDIVES = '462';
    case MALI = '466';
    case MALTA = '470';
    case MARSHALL_ISLANDS = '584';
    case MARTINIQUE = '474';
    case MAURITANIA = '478';
    case MAURITIUS = '480';
    case MAYOTTE = '175';
    case MEXICO = '484';
    case MICRONESIA = '583';
    case MOLDOVA = '498';
    case MONACO = '492';
    case MONGOLIA = '496';
    case MONTENEGRO = '499';
    case MONTSERRAT = '500';
    case MOROCCO = '504';
    case MOZAMBIQUE = '508';
    case MYANMAR_BURMA = '104';
    case NAMIBIA = '516';
    case NAURU = '520';
    case NEPAL = '524';
    case NETHERLANDS = '528';
    case NEW_CALEDONIA = '540';
    case NEW_ZEALAND = '554';
    case NICARAGUA = '558';
    case NIGER = '562';
    case NIGERIA = '566';
    case NIUE = '570';
    case NORFOLK_ISLAND = '574';
    case NORTH_KOREA = '408';
    case NORTH_MACEDONIA = '807';
    case NORTHERN_MARIANA_ISLANDS = '580';
    case NORWAY = '578';
    case OMAN = '512';
    case PAKISTAN = '586';
    case PALAU = '585';
    case PALESTINIAN_TERRITORIES = '275';
    case PANAMA = '591';
    case PAPUA_NEW_GUINEA = '598';
    case PARAGUAY = '600';
    case PERU = '604';
    case PHILIPPINES = '608';
    case PITCAIRN_ISLANDS = '612';
    case POLAND = '616';
    case PORTUGAL = '620';
    case PUERTO_RICO = '630';
    case QATAR = '634';
    case REUNION = '638';
    case ROMANIA = '642';
    case RUSSIA = '643';
    case RWANDA = '646';
    case SAMOA = '882';
    case SAN_MARINO = '674';
    case SAO_TOME_PRINCIPE = '678';
    case SAUDI_ARABIA = '682';
    case SENEGAL = '686';
    case SERBIA = '688';
    case SEYCHELLES = '690';
    case SIERRA_LEONE = '694';
    case SINGAPORE = '702';
    case SINT_MAARTEN = '534';
    case SLOVAKIA = '703';
    case SLOVENIA = '705';
    case SOLOMON_ISLANDS = '090';
    case SOMALIA = '706';
    case SOUTH_AFRICA = '710';
    case SOUTH_GEORGIA_SOUTH_SANDWICH_ISLANDS = '239';
    case SOUTH_KOREA = '410';
    case SOUTH_SUDAN = '728';
    case SPAIN = '724';
    case SRI_LANKA = '144';
    case ST_BARTHELEMY = '652';
    case ST_HELENA = '654';
    case ST_KITTS_NEVIS = '659';
    case ST_LUCIA = '662';
    case ST_MARTIN = '663';
    case ST_PIERRE_MIQUELON = '666';
    case ST_VINCENT_GRENADINES = '670';
    case SUDAN = '729';
    case SURINAME = '740';
    case SVALBARD_JAN_MAYEN = '744';
    case SWEDEN = '752';
    case SWITZERLAND = '756';
    case SYRIA = '760';
    case TAIWAN = '158';
    case TAJIKISTAN = '762';
    case TANZANIA = '834';
    case THAILAND = '764';
    case TIMOR_LESTE = '626';
    case TOGO = '768';
    case TOKELAU = '772';
    case TONGA = '776';
    case TRINIDAD_TOBAGO = '780';
    case TUNISIA = '788';
    case TURKEY = '792';
    case TURKMENISTAN = '795';
    case TURKS_CAICOS_ISLANDS = '796';
    case TUVALU = '798';
    case U_S_OUTLYING_ISLANDS = '581';
    case U_S_VIRGIN_ISLANDS = '850';
    case UGANDA = '800';
    case UKRAINE = '804';
    case UNITED_ARAB_EMIRATES = '784';
    case UNITED_KINGDOM = '826';
    case UNITED_STATES = '840';
    case URUGUAY = '858';
    case UZBEKISTAN = '860';
    case VANUATU = '548';
    case VATICAN_CITY = '336';
    case VENEZUELA = '862';
    case VIETNAM = '704';
    case WALLIS_FUTUNA = '876';
    case WESTERN_SAHARA = '732';
    case YEMEN = '887';
    case ZAMBIA = '894';
    case ZIMBABWE = '716';

    public function asAlpha2(): Alpha2
    {
        return match($this) {
            self::AFGHANISTAN => Alpha2::AFGHANISTAN,
            self::AALAND_ISLANDS => Alpha2::AALAND_ISLANDS,
            self::ALBANIA => Alpha2::ALBANIA,
            self::ALGERIA => Alpha2::ALGERIA,
            self::AMERICAN_SAMOA => Alpha2::AMERICAN_SAMOA,
            self::ANDORRA => Alpha2::ANDORRA,
            self::ANGOLA => Alpha2::ANGOLA,
            self::ANGUILLA => Alpha2::ANGUILLA,
            self::ANTARCTICA => Alpha2::ANTARCTICA,
            self::ANTIGUA_BARBUDA => Alpha2::ANTIGUA_BARBUDA,
            self::ARGENTINA => Alpha2::ARGENTINA,
            self::ARMENIA => Alpha2::ARMENIA,
            self::ARUBA => Alpha2::ARUBA,
            self::AUSTRALIA => Alpha2::AUSTRALIA,
            self::AUSTRIA => Alpha2::AUSTRIA,
            self::AZERBAIJAN => Alpha2::AZERBAIJAN,
            self::BAHAMAS => Alpha2::BAHAMAS,
            self::BAHRAIN => Alpha2::BAHRAIN,
            self::BANGLADESH => Alpha2::BANGLADESH,
            self::BARBADOS => Alpha2::BARBADOS,
            self::BELARUS => Alpha2::BELARUS,
            self::BELGIUM => Alpha2::BELGIUM,
            self::BELIZE => Alpha2::BELIZE,
            self::BENIN => Alpha2::BENIN,
            self::BERMUDA => Alpha2::BERMUDA,
            self::BHUTAN => Alpha2::BHUTAN,
            self::BOLIVIA => Alpha2::BOLIVIA,
            self::BOSNIA_HERZEGOVINA => Alpha2::BOSNIA_HERZEGOVINA,
            self::BOTSWANA => Alpha2::BOTSWANA,
            self::BOUVET_ISLAND => Alpha2::BOUVET_ISLAND,
            self::BRAZIL => Alpha2::BRAZIL,
            self::BRITISH_INDIAN_OCEAN_TERRITORY => Alpha2::BRITISH_INDIAN_OCEAN_TERRITORY,
            self::BRITISH_VIRGIN_ISLANDS => Alpha2::BRITISH_VIRGIN_ISLANDS,
            self::BRUNEI => Alpha2::BRUNEI,
            self::BULGARIA => Alpha2::BULGARIA,
            self::BURKINA_FASO => Alpha2::BURKINA_FASO,
            self::BURUNDI => Alpha2::BURUNDI,
            self::CAMBODIA => Alpha2::CAMBODIA,
            self::CAMEROON => Alpha2::CAMEROON,
            self::CANADA => Alpha2::CANADA,
            self::CAPE_VERDE => Alpha2::CAPE_VERDE,
            self::CARIBBEAN_NETHERLANDS => Alpha2::CARIBBEAN_NETHERLANDS,
            self::CAYMAN_ISLANDS => Alpha2::CAYMAN_ISLANDS,
            self::CENTRAL_AFRICAN_REPUBLIC => Alpha2::CENTRAL_AFRICAN_REPUBLIC,
            self::CHAD => Alpha2::CHAD,
            self::CHILE => Alpha2::CHILE,
            self::CHINA => Alpha2::CHINA,
            self::CHRISTMAS_ISLAND => Alpha2::CHRISTMAS_ISLAND,
            self::COCOS_KEELING_ISLANDS => Alpha2::COCOS_KEELING_ISLANDS,
            self::COLOMBIA => Alpha2::COLOMBIA,
            self::COMOROS => Alpha2::COMOROS,
            self::CONGO_BRAZZAVILLE => Alpha2::CONGO_BRAZZAVILLE,
            self::CONGO_KINSHASA => Alpha2::CONGO_KINSHASA,
            self::COOK_ISLANDS => Alpha2::COOK_ISLANDS,
            self::COSTA_RICA => Alpha2::COSTA_RICA,
            self::COTE_D_IVOIRE => Alpha2::COTE_D_IVOIRE,
            self::CROATIA => Alpha2::CROATIA,
            self::CUBA => Alpha2::CUBA,
            self::CURACAO => Alpha2::CURACAO,
            self::CYPRUS => Alpha2::CYPRUS,
            self::CZECHIA => Alpha2::CZECHIA,
            self::DENMARK => Alpha2::DENMARK,
            self::DJIBOUTI => Alpha2::DJIBOUTI,
            self::DOMINICA => Alpha2::DOMINICA,
            self::DOMINICAN_REPUBLIC => Alpha2::DOMINICAN_REPUBLIC,
            self::ECUADOR => Alpha2::ECUADOR,
            self::EGYPT => Alpha2::EGYPT,
            self::EL_SALVADOR => Alpha2::EL_SALVADOR,
            self::EQUATORIAL_GUINEA => Alpha2::EQUATORIAL_GUINEA,
            self::ERITREA => Alpha2::ERITREA,
            self::ESTONIA => Alpha2::ESTONIA,
            self::ESWATINI => Alpha2::ESWATINI,
            self::ETHIOPIA => Alpha2::ETHIOPIA,
            self::FALKLAND_ISLANDS => Alpha2::FALKLAND_ISLANDS,
            self::FAROE_ISLANDS => Alpha2::FAROE_ISLANDS,
            self::FIJI => Alpha2::FIJI,
            self::FINLAND => Alpha2::FINLAND,
            self::FRANCE => Alpha2::FRANCE,
            self::FRENCH_GUIANA => Alpha2::FRENCH_GUIANA,
            self::FRENCH_POLYNESIA => Alpha2::FRENCH_POLYNESIA,
            self::FRENCH_SOUTHERN_TERRITORIES => Alpha2::FRENCH_SOUTHERN_TERRITORIES,
            self::GABON => Alpha2::GABON,
            self::GAMBIA => Alpha2::GAMBIA,
            self::GEORGIA => Alpha2::GEORGIA,
            self::GERMANY => Alpha2::GERMANY,
            self::GHANA => Alpha2::GHANA,
            self::GIBRALTAR => Alpha2::GIBRALTAR,
            self::GREECE => Alpha2::GREECE,
            self::GREENLAND => Alpha2::GREENLAND,
            self::GRENADA => Alpha2::GRENADA,
            self::GUADELOUPE => Alpha2::GUADELOUPE,
            self::GUAM => Alpha2::GUAM,
            self::GUATEMALA => Alpha2::GUATEMALA,
            self::GUERNSEY => Alpha2::GUERNSEY,
            self::GUINEA => Alpha2::GUINEA,
            self::GUINEA_BISSAU => Alpha2::GUINEA_BISSAU,
            self::GUYANA => Alpha2::GUYANA,
            self::HAITI => Alpha2::HAITI,
            self::HEARD_MCDONALD_ISLANDS => Alpha2::HEARD_MCDONALD_ISLANDS,
            self::HONDURAS => Alpha2::HONDURAS,
            self::HONG_KONG_SAR_CHINA => Alpha2::HONG_KONG_SAR_CHINA,
            self::HUNGARY => Alpha2::HUNGARY,
            self::ICELAND => Alpha2::ICELAND,
            self::INDIA => Alpha2::INDIA,
            self::INDONESIA => Alpha2::INDONESIA,
            self::IRAN => Alpha2::IRAN,
            self::IRAQ => Alpha2::IRAQ,
            self::IRELAND => Alpha2::IRELAND,
            self::ISLE_OF_MAN => Alpha2::ISLE_OF_MAN,
            self::ISRAEL => Alpha2::ISRAEL,
            self::ITALY => Alpha2::ITALY,
            self::JAMAICA => Alpha2::JAMAICA,
            self::JAPAN => Alpha2::JAPAN,
            self::JERSEY => Alpha2::JERSEY,
            self::JORDAN => Alpha2::JORDAN,
            self::KAZAKHSTAN => Alpha2::KAZAKHSTAN,
            self::KENYA => Alpha2::KENYA,
            self::KIRIBATI => Alpha2::KIRIBATI,
            self::KUWAIT => Alpha2::KUWAIT,
            self::KYRGYZSTAN => Alpha2::KYRGYZSTAN,
            self::LAOS => Alpha2::LAOS,
            self::LATVIA => Alpha2::LATVIA,
            self::LEBANON => Alpha2::LEBANON,
            self::LESOTHO => Alpha2::LESOTHO,
            self::LIBERIA => Alpha2::LIBERIA,
            self::LIBYA => Alpha2::LIBYA,
            self::LIECHTENSTEIN => Alpha2::LIECHTENSTEIN,
            self::LITHUANIA => Alpha2::LITHUANIA,
            self::LUXEMBOURG => Alpha2::LUXEMBOURG,
            self::MACAO_SAR_CHINA => Alpha2::MACAO_SAR_CHINA,
            self::MADAGASCAR => Alpha2::MADAGASCAR,
            self::MALAWI => Alpha2::MALAWI,
            self::MALAYSIA => Alpha2::MALAYSIA,
            self::MALDIVES => Alpha2::MALDIVES,
            self::MALI => Alpha2::MALI,
            self::MALTA => Alpha2::MALTA,
            self::MARSHALL_ISLANDS => Alpha2::MARSHALL_ISLANDS,
            self::MARTINIQUE => Alpha2::MARTINIQUE,
            self::MAURITANIA => Alpha2::MAURITANIA,
            self::MAURITIUS => Alpha2::MAURITIUS,
            self::MAYOTTE => Alpha2::MAYOTTE,
            self::MEXICO => Alpha2::MEXICO,
            self::MICRONESIA => Alpha2::MICRONESIA,
            self::MOLDOVA => Alpha2::MOLDOVA,
            self::MONACO => Alpha2::MONACO,
            self::MONGOLIA => Alpha2::MONGOLIA,
            self::MONTENEGRO => Alpha2::MONTENEGRO,
            self::MONTSERRAT => Alpha2::MONTSERRAT,
            self::MOROCCO => Alpha2::MOROCCO,
            self::MOZAMBIQUE => Alpha2::MOZAMBIQUE,
            self::MYANMAR_BURMA => Alpha2::MYANMAR_BURMA,
            self::NAMIBIA => Alpha2::NAMIBIA,
            self::NAURU => Alpha2::NAURU,
            self::NEPAL => Alpha2::NEPAL,
            self::NETHERLANDS => Alpha2::NETHERLANDS,
            self::NEW_CALEDONIA => Alpha2::NEW_CALEDONIA,
            self::NEW_ZEALAND => Alpha2::NEW_ZEALAND,
            self::NICARAGUA => Alpha2::NICARAGUA,
            self::NIGER => Alpha2::NIGER,
            self::NIGERIA => Alpha2::NIGERIA,
            self::NIUE => Alpha2::NIUE,
            self::NORFOLK_ISLAND => Alpha2::NORFOLK_ISLAND,
            self::NORTH_KOREA => Alpha2::NORTH_KOREA,
            self::NORTH_MACEDONIA => Alpha2::NORTH_MACEDONIA,
            self::NORTHERN_MARIANA_ISLANDS => Alpha2::NORTHERN_MARIANA_ISLANDS,
            self::NORWAY => Alpha2::NORWAY,
            self::OMAN => Alpha2::OMAN,
            self::PAKISTAN => Alpha2::PAKISTAN,
            self::PALAU => Alpha2::PALAU,
            self::PALESTINIAN_TERRITORIES => Alpha2::PALESTINIAN_TERRITORIES,
            self::PANAMA => Alpha2::PANAMA,
            self::PAPUA_NEW_GUINEA => Alpha2::PAPUA_NEW_GUINEA,
            self::PARAGUAY => Alpha2::PARAGUAY,
            self::PERU => Alpha2::PERU,
            self::PHILIPPINES => Alpha2::PHILIPPINES,
            self::PITCAIRN_ISLANDS => Alpha2::PITCAIRN_ISLANDS,
            self::POLAND => Alpha2::POLAND,
            self::PORTUGAL => Alpha2::PORTUGAL,
            self::PUERTO_RICO => Alpha2::PUERTO_RICO,
            self::QATAR => Alpha2::QATAR,
            self::REUNION => Alpha2::REUNION,
            self::ROMANIA => Alpha2::ROMANIA,
            self::RUSSIA => Alpha2::RUSSIA,
            self::RWANDA => Alpha2::RWANDA,
            self::SAMOA => Alpha2::SAMOA,
            self::SAN_MARINO => Alpha2::SAN_MARINO,
            self::SAO_TOME_PRINCIPE => Alpha2::SAO_TOME_PRINCIPE,
            self::SAUDI_ARABIA => Alpha2::SAUDI_ARABIA,
            self::SENEGAL => Alpha2::SENEGAL,
            self::SERBIA => Alpha2::SERBIA,
            self::SEYCHELLES => Alpha2::SEYCHELLES,
            self::SIERRA_LEONE => Alpha2::SIERRA_LEONE,
            self::SINGAPORE => Alpha2::SINGAPORE,
            self::SINT_MAARTEN => Alpha2::SINT_MAARTEN,
            self::SLOVAKIA => Alpha2::SLOVAKIA,
            self::SLOVENIA => Alpha2::SLOVENIA,
            self::SOLOMON_ISLANDS => Alpha2::SOLOMON_ISLANDS,
            self::SOMALIA => Alpha2::SOMALIA,
            self::SOUTH_AFRICA => Alpha2::SOUTH_AFRICA,
            self::SOUTH_GEORGIA_SOUTH_SANDWICH_ISLANDS => Alpha2::SOUTH_GEORGIA_SOUTH_SANDWICH_ISLANDS,
            self::SOUTH_KOREA => Alpha2::SOUTH_KOREA,
            self::SOUTH_SUDAN => Alpha2::SOUTH_SUDAN,
            self::SPAIN => Alpha2::SPAIN,
            self::SRI_LANKA => Alpha2::SRI_LANKA,
            self::ST_BARTHELEMY => Alpha2::ST_BARTHELEMY,
            self::ST_HELENA => Alpha2::ST_HELENA,
            self::ST_KITTS_NEVIS => Alpha2::ST_KITTS_NEVIS,
            self::ST_LUCIA => Alpha2::ST_LUCIA,
            self::ST_MARTIN => Alpha2::ST_MARTIN,
            self::ST_PIERRE_MIQUELON => Alpha2::ST_PIERRE_MIQUELON,
            self::ST_VINCENT_GRENADINES => Alpha2::ST_VINCENT_GRENADINES,
            self::SUDAN => Alpha2::SUDAN,
            self::SURINAME => Alpha2::SURINAME,
            self::SVALBARD_JAN_MAYEN => Alpha2::SVALBARD_JAN_MAYEN,
            self::SWEDEN => Alpha2::SWEDEN,
            self::SWITZERLAND => Alpha2::SWITZERLAND,
            self::SYRIA => Alpha2::SYRIA,
            self::TAIWAN => Alpha2::TAIWAN,
            self::TAJIKISTAN => Alpha2::TAJIKISTAN,
            self::TANZANIA => Alpha2::TANZANIA,
            self::THAILAND => Alpha2::THAILAND,
            self::TIMOR_LESTE => Alpha2::TIMOR_LESTE,
            self::TOGO => Alpha2::TOGO,
            self::TOKELAU => Alpha2::TOKELAU,
            self::TONGA => Alpha2::TONGA,
            self::TRINIDAD_TOBAGO => Alpha2::TRINIDAD_TOBAGO,
            self::TUNISIA => Alpha2::TUNISIA,
            self::TURKEY => Alpha2::TURKEY,
            self::TURKMENISTAN => Alpha2::TURKMENISTAN,
            self::TURKS_CAICOS_ISLANDS => Alpha2::TURKS_CAICOS_ISLANDS,
            self::TUVALU => Alpha2::TUVALU,
            self::U_S_OUTLYING_ISLANDS => Alpha2::U_S_OUTLYING_ISLANDS,
            self::U_S_VIRGIN_ISLANDS => Alpha2::U_S_VIRGIN_ISLANDS,
            self::UGANDA => Alpha2::UGANDA,
            self::UKRAINE => Alpha2::UKRAINE,
            self::UNITED_ARAB_EMIRATES => Alpha2::UNITED_ARAB_EMIRATES,
            self::UNITED_KINGDOM => Alpha2::UNITED_KINGDOM,
            self::UNITED_STATES => Alpha2::UNITED_STATES,
            self::URUGUAY => Alpha2::URUGUAY,
            self::UZBEKISTAN => Alpha2::UZBEKISTAN,
            self::VANUATU => Alpha2::VANUATU,
            self::VATICAN_CITY => Alpha2::VATICAN_CITY,
            self::VENEZUELA => Alpha2::VENEZUELA,
            self::VIETNAM => Alpha2::VIETNAM,
            self::WALLIS_FUTUNA => Alpha2::WALLIS_FUTUNA,
            self::WESTERN_SAHARA => Alpha2::WESTERN_SAHARA,
            self::YEMEN => Alpha2::YEMEN,
            self::ZAMBIA => Alpha2::ZAMBIA,
            self::ZIMBABWE => Alpha2::ZIMBABWE
        };
    }

    public function asAlpha3(): Alpha3
    {
        return match($this) {
            self::AFGHANISTAN => Alpha3::AFGHANISTAN,
            self::AALAND_ISLANDS => Alpha3::AALAND_ISLANDS,
            self::ALBANIA => Alpha3::ALBANIA,
            self::ALGERIA => Alpha3::ALGERIA,
            self::AMERICAN_SAMOA => Alpha3::AMERICAN_SAMOA,
            self::ANDORRA => Alpha3::ANDORRA,
            self::ANGOLA => Alpha3::ANGOLA,
            self::ANGUILLA => Alpha3::ANGUILLA,
            self::ANTARCTICA => Alpha3::ANTARCTICA,
            self::ANTIGUA_BARBUDA => Alpha3::ANTIGUA_BARBUDA,
            self::ARGENTINA => Alpha3::ARGENTINA,
            self::ARMENIA => Alpha3::ARMENIA,
            self::ARUBA => Alpha3::ARUBA,
            self::AUSTRALIA => Alpha3::AUSTRALIA,
            self::AUSTRIA => Alpha3::AUSTRIA,
            self::AZERBAIJAN => Alpha3::AZERBAIJAN,
            self::BAHAMAS => Alpha3::BAHAMAS,
            self::BAHRAIN => Alpha3::BAHRAIN,
            self::BANGLADESH => Alpha3::BANGLADESH,
            self::BARBADOS => Alpha3::BARBADOS,
            self::BELARUS => Alpha3::BELARUS,
            self::BELGIUM => Alpha3::BELGIUM,
            self::BELIZE => Alpha3::BELIZE,
            self::BENIN => Alpha3::BENIN,
            self::BERMUDA => Alpha3::BERMUDA,
            self::BHUTAN => Alpha3::BHUTAN,
            self::BOLIVIA => Alpha3::BOLIVIA,
            self::BOSNIA_HERZEGOVINA => Alpha3::BOSNIA_HERZEGOVINA,
            self::BOTSWANA => Alpha3::BOTSWANA,
            self::BOUVET_ISLAND => Alpha3::BOUVET_ISLAND,
            self::BRAZIL => Alpha3::BRAZIL,
            self::BRITISH_INDIAN_OCEAN_TERRITORY => Alpha3::BRITISH_INDIAN_OCEAN_TERRITORY,
            self::BRITISH_VIRGIN_ISLANDS => Alpha3::BRITISH_VIRGIN_ISLANDS,
            self::BRUNEI => Alpha3::BRUNEI,
            self::BULGARIA => Alpha3::BULGARIA,
            self::BURKINA_FASO => Alpha3::BURKINA_FASO,
            self::BURUNDI => Alpha3::BURUNDI,
            self::CAMBODIA => Alpha3::CAMBODIA,
            self::CAMEROON => Alpha3::CAMEROON,
            self::CANADA => Alpha3::CANADA,
            self::CAPE_VERDE => Alpha3::CAPE_VERDE,
            self::CARIBBEAN_NETHERLANDS => Alpha3::CARIBBEAN_NETHERLANDS,
            self::CAYMAN_ISLANDS => Alpha3::CAYMAN_ISLANDS,
            self::CENTRAL_AFRICAN_REPUBLIC => Alpha3::CENTRAL_AFRICAN_REPUBLIC,
            self::CHAD => Alpha3::CHAD,
            self::CHILE => Alpha3::CHILE,
            self::CHINA => Alpha3::CHINA,
            self::CHRISTMAS_ISLAND => Alpha3::CHRISTMAS_ISLAND,
            self::COCOS_KEELING_ISLANDS => Alpha3::COCOS_KEELING_ISLANDS,
            self::COLOMBIA => Alpha3::COLOMBIA,
            self::COMOROS => Alpha3::COMOROS,
            self::CONGO_BRAZZAVILLE => Alpha3::CONGO_BRAZZAVILLE,
            self::CONGO_KINSHASA => Alpha3::CONGO_KINSHASA,
            self::COOK_ISLANDS => Alpha3::COOK_ISLANDS,
            self::COSTA_RICA => Alpha3::COSTA_RICA,
            self::COTE_D_IVOIRE => Alpha3::COTE_D_IVOIRE,
            self::CROATIA => Alpha3::CROATIA,
            self::CUBA => Alpha3::CUBA,
            self::CURACAO => Alpha3::CURACAO,
            self::CYPRUS => Alpha3::CYPRUS,
            self::CZECHIA => Alpha3::CZECHIA,
            self::DENMARK => Alpha3::DENMARK,
            self::DJIBOUTI => Alpha3::DJIBOUTI,
            self::DOMINICA => Alpha3::DOMINICA,
            self::DOMINICAN_REPUBLIC => Alpha3::DOMINICAN_REPUBLIC,
            self::ECUADOR => Alpha3::ECUADOR,
            self::EGYPT => Alpha3::EGYPT,
            self::EL_SALVADOR => Alpha3::EL_SALVADOR,
            self::EQUATORIAL_GUINEA => Alpha3::EQUATORIAL_GUINEA,
            self::ERITREA => Alpha3::ERITREA,
            self::ESTONIA => Alpha3::ESTONIA,
            self::ESWATINI => Alpha3::ESWATINI,
            self::ETHIOPIA => Alpha3::ETHIOPIA,
            self::FALKLAND_ISLANDS => Alpha3::FALKLAND_ISLANDS,
            self::FAROE_ISLANDS => Alpha3::FAROE_ISLANDS,
            self::FIJI => Alpha3::FIJI,
            self::FINLAND => Alpha3::FINLAND,
            self::FRANCE => Alpha3::FRANCE,
            self::FRENCH_GUIANA => Alpha3::FRENCH_GUIANA,
            self::FRENCH_POLYNESIA => Alpha3::FRENCH_POLYNESIA,
            self::FRENCH_SOUTHERN_TERRITORIES => Alpha3::FRENCH_SOUTHERN_TERRITORIES,
            self::GABON => Alpha3::GABON,
            self::GAMBIA => Alpha3::GAMBIA,
            self::GEORGIA => Alpha3::GEORGIA,
            self::GERMANY => Alpha3::GERMANY,
            self::GHANA => Alpha3::GHANA,
            self::GIBRALTAR => Alpha3::GIBRALTAR,
            self::GREECE => Alpha3::GREECE,
            self::GREENLAND => Alpha3::GREENLAND,
            self::GRENADA => Alpha3::GRENADA,
            self::GUADELOUPE => Alpha3::GUADELOUPE,
            self::GUAM => Alpha3::GUAM,
            self::GUATEMALA => Alpha3::GUATEMALA,
            self::GUERNSEY => Alpha3::GUERNSEY,
            self::GUINEA => Alpha3::GUINEA,
            self::GUINEA_BISSAU => Alpha3::GUINEA_BISSAU,
            self::GUYANA => Alpha3::GUYANA,
            self::HAITI => Alpha3::HAITI,
            self::HEARD_MCDONALD_ISLANDS => Alpha3::HEARD_MCDONALD_ISLANDS,
            self::HONDURAS => Alpha3::HONDURAS,
            self::HONG_KONG_SAR_CHINA => Alpha3::HONG_KONG_SAR_CHINA,
            self::HUNGARY => Alpha3::HUNGARY,
            self::ICELAND => Alpha3::ICELAND,
            self::INDIA => Alpha3::INDIA,
            self::INDONESIA => Alpha3::INDONESIA,
            self::IRAN => Alpha3::IRAN,
            self::IRAQ => Alpha3::IRAQ,
            self::IRELAND => Alpha3::IRELAND,
            self::ISLE_OF_MAN => Alpha3::ISLE_OF_MAN,
            self::ISRAEL => Alpha3::ISRAEL,
            self::ITALY => Alpha3::ITALY,
            self::JAMAICA => Alpha3::JAMAICA,
            self::JAPAN => Alpha3::JAPAN,
            self::JERSEY => Alpha3::JERSEY,
            self::JORDAN => Alpha3::JORDAN,
            self::KAZAKHSTAN => Alpha3::KAZAKHSTAN,
            self::KENYA => Alpha3::KENYA,
            self::KIRIBATI => Alpha3::KIRIBATI,
            self::KUWAIT => Alpha3::KUWAIT,
            self::KYRGYZSTAN => Alpha3::KYRGYZSTAN,
            self::LAOS => Alpha3::LAOS,
            self::LATVIA => Alpha3::LATVIA,
            self::LEBANON => Alpha3::LEBANON,
            self::LESOTHO => Alpha3::LESOTHO,
            self::LIBERIA => Alpha3::LIBERIA,
            self::LIBYA => Alpha3::LIBYA,
            self::LIECHTENSTEIN => Alpha3::LIECHTENSTEIN,
            self::LITHUANIA => Alpha3::LITHUANIA,
            self::LUXEMBOURG => Alpha3::LUXEMBOURG,
            self::MACAO_SAR_CHINA => Alpha3::MACAO_SAR_CHINA,
            self::MADAGASCAR => Alpha3::MADAGASCAR,
            self::MALAWI => Alpha3::MALAWI,
            self::MALAYSIA => Alpha3::MALAYSIA,
            self::MALDIVES => Alpha3::MALDIVES,
            self::MALI => Alpha3::MALI,
            self::MALTA => Alpha3::MALTA,
            self::MARSHALL_ISLANDS => Alpha3::MARSHALL_ISLANDS,
            self::MARTINIQUE => Alpha3::MARTINIQUE,
            self::MAURITANIA => Alpha3::MAURITANIA,
            self::MAURITIUS => Alpha3::MAURITIUS,
            self::MAYOTTE => Alpha3::MAYOTTE,
            self::MEXICO => Alpha3::MEXICO,
            self::MICRONESIA => Alpha3::MICRONESIA,
            self::MOLDOVA => Alpha3::MOLDOVA,
            self::MONACO => Alpha3::MONACO,
            self::MONGOLIA => Alpha3::MONGOLIA,
            self::MONTENEGRO => Alpha3::MONTENEGRO,
            self::MONTSERRAT => Alpha3::MONTSERRAT,
            self::MOROCCO => Alpha3::MOROCCO,
            self::MOZAMBIQUE => Alpha3::MOZAMBIQUE,
            self::MYANMAR_BURMA => Alpha3::MYANMAR_BURMA,
            self::NAMIBIA => Alpha3::NAMIBIA,
            self::NAURU => Alpha3::NAURU,
            self::NEPAL => Alpha3::NEPAL,
            self::NETHERLANDS => Alpha3::NETHERLANDS,
            self::NEW_CALEDONIA => Alpha3::NEW_CALEDONIA,
            self::NEW_ZEALAND => Alpha3::NEW_ZEALAND,
            self::NICARAGUA => Alpha3::NICARAGUA,
            self::NIGER => Alpha3::NIGER,
            self::NIGERIA => Alpha3::NIGERIA,
            self::NIUE => Alpha3::NIUE,
            self::NORFOLK_ISLAND => Alpha3::NORFOLK_ISLAND,
            self::NORTH_KOREA => Alpha3::NORTH_KOREA,
            self::NORTH_MACEDONIA => Alpha3::NORTH_MACEDONIA,
            self::NORTHERN_MARIANA_ISLANDS => Alpha3::NORTHERN_MARIANA_ISLANDS,
            self::NORWAY => Alpha3::NORWAY,
            self::OMAN => Alpha3::OMAN,
            self::PAKISTAN => Alpha3::PAKISTAN,
            self::PALAU => Alpha3::PALAU,
            self::PALESTINIAN_TERRITORIES => Alpha3::PALESTINIAN_TERRITORIES,
            self::PANAMA => Alpha3::PANAMA,
            self::PAPUA_NEW_GUINEA => Alpha3::PAPUA_NEW_GUINEA,
            self::PARAGUAY => Alpha3::PARAGUAY,
            self::PERU => Alpha3::PERU,
            self::PHILIPPINES => Alpha3::PHILIPPINES,
            self::PITCAIRN_ISLANDS => Alpha3::PITCAIRN_ISLANDS,
            self::POLAND => Alpha3::POLAND,
            self::PORTUGAL => Alpha3::PORTUGAL,
            self::PUERTO_RICO => Alpha3::PUERTO_RICO,
            self::QATAR => Alpha3::QATAR,
            self::REUNION => Alpha3::REUNION,
            self::ROMANIA => Alpha3::ROMANIA,
            self::RUSSIA => Alpha3::RUSSIA,
            self::RWANDA => Alpha3::RWANDA,
            self::SAMOA => Alpha3::SAMOA,
            self::SAN_MARINO => Alpha3::SAN_MARINO,
            self::SAO_TOME_PRINCIPE => Alpha3::SAO_TOME_PRINCIPE,
            self::SAUDI_ARABIA => Alpha3::SAUDI_ARABIA,
            self::SENEGAL => Alpha3::SENEGAL,
            self::SERBIA => Alpha3::SERBIA,
            self::SEYCHELLES => Alpha3::SEYCHELLES,
            self::SIERRA_LEONE => Alpha3::SIERRA_LEONE,
            self::SINGAPORE => Alpha3::SINGAPORE,
            self::SINT_MAARTEN => Alpha3::SINT_MAARTEN,
            self::SLOVAKIA => Alpha3::SLOVAKIA,
            self::SLOVENIA => Alpha3::SLOVENIA,
            self::SOLOMON_ISLANDS => Alpha3::SOLOMON_ISLANDS,
            self::SOMALIA => Alpha3::SOMALIA,
            self::SOUTH_AFRICA => Alpha3::SOUTH_AFRICA,
            self::SOUTH_GEORGIA_SOUTH_SANDWICH_ISLANDS => Alpha3::SOUTH_GEORGIA_SOUTH_SANDWICH_ISLANDS,
            self::SOUTH_KOREA => Alpha3::SOUTH_KOREA,
            self::SOUTH_SUDAN => Alpha3::SOUTH_SUDAN,
            self::SPAIN => Alpha3::SPAIN,
            self::SRI_LANKA => Alpha3::SRI_LANKA,
            self::ST_BARTHELEMY => Alpha3::ST_BARTHELEMY,
            self::ST_HELENA => Alpha3::ST_HELENA,
            self::ST_KITTS_NEVIS => Alpha3::ST_KITTS_NEVIS,
            self::ST_LUCIA => Alpha3::ST_LUCIA,
            self::ST_MARTIN => Alpha3::ST_MARTIN,
            self::ST_PIERRE_MIQUELON => Alpha3::ST_PIERRE_MIQUELON,
            self::ST_VINCENT_GRENADINES => Alpha3::ST_VINCENT_GRENADINES,
            self::SUDAN => Alpha3::SUDAN,
            self::SURINAME => Alpha3::SURINAME,
            self::SVALBARD_JAN_MAYEN => Alpha3::SVALBARD_JAN_MAYEN,
            self::SWEDEN => Alpha3::SWEDEN,
            self::SWITZERLAND => Alpha3::SWITZERLAND,
            self::SYRIA => Alpha3::SYRIA,
            self::TAIWAN => Alpha3::TAIWAN,
            self::TAJIKISTAN => Alpha3::TAJIKISTAN,
            self::TANZANIA => Alpha3::TANZANIA,
            self::THAILAND => Alpha3::THAILAND,
            self::TIMOR_LESTE => Alpha3::TIMOR_LESTE,
            self::TOGO => Alpha3::TOGO,
            self::TOKELAU => Alpha3::TOKELAU,
            self::TONGA => Alpha3::TONGA,
            self::TRINIDAD_TOBAGO => Alpha3::TRINIDAD_TOBAGO,
            self::TUNISIA => Alpha3::TUNISIA,
            self::TURKEY => Alpha3::TURKEY,
            self::TURKMENISTAN => Alpha3::TURKMENISTAN,
            self::TURKS_CAICOS_ISLANDS => Alpha3::TURKS_CAICOS_ISLANDS,
            self::TUVALU => Alpha3::TUVALU,
            self::U_S_OUTLYING_ISLANDS => Alpha3::U_S_OUTLYING_ISLANDS,
            self::U_S_VIRGIN_ISLANDS => Alpha3::U_S_VIRGIN_ISLANDS,
            self::UGANDA => Alpha3::UGANDA,
            self::UKRAINE => Alpha3::UKRAINE,
            self::UNITED_ARAB_EMIRATES => Alpha3::UNITED_ARAB_EMIRATES,
            self::UNITED_KINGDOM => Alpha3::UNITED_KINGDOM,
            self::UNITED_STATES => Alpha3::UNITED_STATES,
            self::URUGUAY => Alpha3::URUGUAY,
            self::UZBEKISTAN => Alpha3::UZBEKISTAN,
            self::VANUATU => Alpha3::VANUATU,
            self::VATICAN_CITY => Alpha3::VATICAN_CITY,
            self::VENEZUELA => Alpha3::VENEZUELA,
            self::VIETNAM => Alpha3::VIETNAM,
            self::WALLIS_FUTUNA => Alpha3::WALLIS_FUTUNA,
            self::WESTERN_SAHARA => Alpha3::WESTERN_SAHARA,
            self::YEMEN => Alpha3::YEMEN,
            self::ZAMBIA => Alpha3::ZAMBIA,
            self::ZIMBABWE => Alpha3::ZIMBABWE
        };
    }

    public function asNumeric(): Numeric
    {
        return $this;
    }
}
